/***************************************************************************//**
* \file cyip_mxnnlite_1_0.h
*
* \brief
* MXNNLITE_1_0 IP definitions
*
********************************************************************************
* \copyright
* (c) (2016-2025), Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
*
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#ifndef _CYIP_MXNNLITE_1_0_H_
#define _CYIP_MXNNLITE_1_0_H_

#include "cyip_headers.h"

/*******************************************************************************
*                                 MXNNLITE_1_0
*******************************************************************************/

#define MXNNLITE_1_0_SECTION_SIZE               0x00001000UL

/**
  * \brief MXNNLITE_1_0
  */
typedef struct {
   __IM uint32_t RESERVED;
  __IOM uint32_t WEIGHTSTREAMERBASEADDR;        /*!< 0x00000004  */
  __IOM uint32_t WEIGHTSTREAMEROFFSET;          /*!< 0x00000008  */
  __IOM uint32_t WEIGHTSTREAMERKERNELCHANNELTIMESHEIGHTTIMESWIDTH; /*!< 0x0000000C  */
  __IOM uint32_t ACTIVATIONSTREAMERBASEADDR;    /*!< 0x00000010  */
  __IOM uint32_t ACTIVATIONSTREAMEROFFSET;      /*!< 0x00000014  */
  __IOM uint32_t ACTIVATIONSTREAMERKERNELCHANNELTIMESWIDTH; /*!< 0x00000018  */
  __IOM uint32_t ACTIVATIONSTREAMERKERNELHEIGHT; /*!< 0x0000001C  */
  __IOM uint32_t ACTIVATIONSTREAMERREPEATS;     /*!< 0x00000020  */
  __IOM uint32_t ACTIVATIONSTREAMERSTARTCOL;    /*!< 0x00000024  */
  __IOM uint32_t ACTIVATIONSTREAMERSTARTROW;    /*!< 0x00000028  */
  __IOM uint32_t ACTIVATIONSTREAMERCHANNELTIMESWIDTH; /*!< 0x0000002C  */
  __IOM uint32_t ACTIVATIONSTREAMERHEIGHT;      /*!< 0x00000030  */
  __IOM uint32_t ACTIVATIONSTREAMERPADDING;     /*!< 0x00000034  */
  __IOM uint32_t ACTIVATIONSTREAMERSPARSITYMAPBASEADDR; /*!< 0x00000038  */
  __IOM uint32_t OUTSTREAMERBASEADDR;           /*!< 0x0000003C  */
  __IOM uint32_t OUTSTREAMEROUTPUTOFFSET;       /*!< 0x00000040  */
  __IOM uint32_t OUTSTREAMERSCALINGFACTOR;      /*!< 0x00000044  */
  __IOM uint32_t OUTSTREAMERCLIPPINGMASK;       /*!< 0x00000048  */
  __IOM uint32_t BIASBASEADDR;                  /*!< 0x0000004C  */
  __IOM uint32_t STREAMERMODES;                 /*!< 0x00000050  */
  __IOM uint32_t NONZEROWEIGHTSPOINTER;         /*!< 0x00000054 Memory address, which stores the number of the non-zero weights */
  __IOM uint32_t OUTPUTWIDTH;                   /*!< 0x00000058 Output width for one layer */
  __IOM uint32_t OUTPUTHEIGHT;                  /*!< 0x0000005C Output height for one layer */
  __IOM uint32_t STRIDE;                        /*!< 0x00000060 Stride control register */
  __IOM uint32_t INTERPOLATIONLUTADDR;          /*!< 0x00000064  */
   __OM uint32_t INTERPOLATIONLUTWDATA;         /*!< 0x00000068 Write data for calculation of interpolation */
  __IOM uint32_t NNLAYER_ACTIVATION_TYPE_CTL;   /*!< 0x0000006C Select layer type, activation functions and activation size */
  __IOM uint32_t INTR;                          /*!< 0x00000070 Interrupt cause and clear register */
  __IOM uint32_t INTR_SET;                      /*!< 0x00000074 Set INTR_XXX register by software for debug purpose */
  __IOM uint32_t INTR_MASK;                     /*!< 0x00000078 Interrupt mask register. A co-located interrupt cause bit will
                                                                only cause an interrupt when its mask bit is 1 */
  __IOM uint32_t TRIG_MASK;                     /*!< 0x0000007C Trigger mask register. Calculation done for one layer triggers
                                                                DataWire when its mask bit is 1 */
  __IOM uint32_t CMD;                           /*!< 0x00000080 Command register */
   __IM uint32_t INTR_MASKED;                   /*!< 0x00000084 Virtual register for generating the interrupt signal to MCU. It
                                                                is the logical AND of the INTR_XXX and INTR_MASK_XXX register */
   __IM uint32_t STATUS;                        /*!< 0x00000088 Status register */
} MXNNLITE_1_0_Type;                            /*!< Size = 140 (0x8C) */


/* MXNNLITE_1_0.WEIGHTSTREAMERBASEADDR */
#define MXNNLITE_1_0_WEIGHTSTREAMERBASEADDR_WEIGHTSTREAMERBASEADDR_Pos 0UL
#define MXNNLITE_1_0_WEIGHTSTREAMERBASEADDR_WEIGHTSTREAMERBASEADDR_Msk 0xFFFFFFFFUL
/* MXNNLITE_1_0.WEIGHTSTREAMEROFFSET */
#define MXNNLITE_1_0_WEIGHTSTREAMEROFFSET_WEIGHTSTREAMEROFFSET_Pos 0UL
#define MXNNLITE_1_0_WEIGHTSTREAMEROFFSET_WEIGHTSTREAMEROFFSET_Msk 0x1FFUL
/* MXNNLITE_1_0.WEIGHTSTREAMERKERNELCHANNELTIMESHEIGHTTIMESWIDTH */
#define MXNNLITE_1_0_WEIGHTSTREAMERKERNELCHANNELTIMESHEIGHTTIMESWIDTH_WEIGHTSTREAMERKERNELCHANNELTIMESHEIGHTTIMESWIDTH_Pos 0UL
#define MXNNLITE_1_0_WEIGHTSTREAMERKERNELCHANNELTIMESHEIGHTTIMESWIDTH_WEIGHTSTREAMERKERNELCHANNELTIMESHEIGHTTIMESWIDTH_Msk 0x3FFFFUL
/* MXNNLITE_1_0.ACTIVATIONSTREAMERBASEADDR */
#define MXNNLITE_1_0_ACTIVATIONSTREAMERBASEADDR_ACTIVATIONSTREAMERBASEADDR_Pos 0UL
#define MXNNLITE_1_0_ACTIVATIONSTREAMERBASEADDR_ACTIVATIONSTREAMERBASEADDR_Msk 0xFFFFFFFFUL
/* MXNNLITE_1_0.ACTIVATIONSTREAMEROFFSET */
#define MXNNLITE_1_0_ACTIVATIONSTREAMEROFFSET_ACTIVATIONSTREAMEROFFSET_Pos 0UL
#define MXNNLITE_1_0_ACTIVATIONSTREAMEROFFSET_ACTIVATIONSTREAMEROFFSET_Msk 0x1FFFFUL
/* MXNNLITE_1_0.ACTIVATIONSTREAMERKERNELCHANNELTIMESWIDTH */
#define MXNNLITE_1_0_ACTIVATIONSTREAMERKERNELCHANNELTIMESWIDTH_ACTIVATIONSTREAMERKERNELCHANNELTIMESWIDTH_Pos 0UL
#define MXNNLITE_1_0_ACTIVATIONSTREAMERKERNELCHANNELTIMESWIDTH_ACTIVATIONSTREAMERKERNELCHANNELTIMESWIDTH_Msk 0x3FFFFUL
/* MXNNLITE_1_0.ACTIVATIONSTREAMERKERNELHEIGHT */
#define MXNNLITE_1_0_ACTIVATIONSTREAMERKERNELHEIGHT_ACTIVATIONSTREAMERKERNELHEIGHT_Pos 0UL
#define MXNNLITE_1_0_ACTIVATIONSTREAMERKERNELHEIGHT_ACTIVATIONSTREAMERKERNELHEIGHT_Msk 0x1FFFFUL
/* MXNNLITE_1_0.ACTIVATIONSTREAMERREPEATS */
#define MXNNLITE_1_0_ACTIVATIONSTREAMERREPEATS_ACTIVATIONSTREAMERREPEATS_Pos 0UL
#define MXNNLITE_1_0_ACTIVATIONSTREAMERREPEATS_ACTIVATIONSTREAMERREPEATS_Msk 0x3FFFFUL
/* MXNNLITE_1_0.ACTIVATIONSTREAMERSTARTCOL */
#define MXNNLITE_1_0_ACTIVATIONSTREAMERSTARTCOL_ACTIVATIONSTREAMERSTARTCOL_Pos 0UL
#define MXNNLITE_1_0_ACTIVATIONSTREAMERSTARTCOL_ACTIVATIONSTREAMERSTARTCOL_Msk 0x3FFFFUL
/* MXNNLITE_1_0.ACTIVATIONSTREAMERSTARTROW */
#define MXNNLITE_1_0_ACTIVATIONSTREAMERSTARTROW_ACTIVATIONSTREAMERSTARTROW_Pos 0UL
#define MXNNLITE_1_0_ACTIVATIONSTREAMERSTARTROW_ACTIVATIONSTREAMERSTARTROW_Msk 0x3FFFFUL
/* MXNNLITE_1_0.ACTIVATIONSTREAMERCHANNELTIMESWIDTH */
#define MXNNLITE_1_0_ACTIVATIONSTREAMERCHANNELTIMESWIDTH_ACTIVATIONSTREAMERCHANNELTIMESWIDTH_Pos 0UL
#define MXNNLITE_1_0_ACTIVATIONSTREAMERCHANNELTIMESWIDTH_ACTIVATIONSTREAMERCHANNELTIMESWIDTH_Msk 0x1FFFFUL
/* MXNNLITE_1_0.ACTIVATIONSTREAMERHEIGHT */
#define MXNNLITE_1_0_ACTIVATIONSTREAMERHEIGHT_ACTIVATIONSTREAMERHEIGHT_Pos 0UL
#define MXNNLITE_1_0_ACTIVATIONSTREAMERHEIGHT_ACTIVATIONSTREAMERHEIGHT_Msk 0x1FFFFUL
/* MXNNLITE_1_0.ACTIVATIONSTREAMERPADDING */
#define MXNNLITE_1_0_ACTIVATIONSTREAMERPADDING_ACTIVATIONSTREAMERPADVALUE_Pos 0UL
#define MXNNLITE_1_0_ACTIVATIONSTREAMERPADDING_ACTIVATIONSTREAMERPADVALUE_Msk 0xFFFFUL
/* MXNNLITE_1_0.ACTIVATIONSTREAMERSPARSITYMAPBASEADDR */
#define MXNNLITE_1_0_ACTIVATIONSTREAMERSPARSITYMAPBASEADDR_ACTIVATIONSTREAMERSPARSITYMAPBASEADDR_Pos 0UL
#define MXNNLITE_1_0_ACTIVATIONSTREAMERSPARSITYMAPBASEADDR_ACTIVATIONSTREAMERSPARSITYMAPBASEADDR_Msk 0xFFFFFFFFUL
/* MXNNLITE_1_0.OUTSTREAMERBASEADDR */
#define MXNNLITE_1_0_OUTSTREAMERBASEADDR_OUTSTREAMERBASEADDR_Pos 0UL
#define MXNNLITE_1_0_OUTSTREAMERBASEADDR_OUTSTREAMERBASEADDR_Msk 0xFFFFFFFFUL
/* MXNNLITE_1_0.OUTSTREAMEROUTPUTOFFSET */
#define MXNNLITE_1_0_OUTSTREAMEROUTPUTOFFSET_OUTSTREAMEROUTPUTOFFSET_Pos 0UL
#define MXNNLITE_1_0_OUTSTREAMEROUTPUTOFFSET_OUTSTREAMEROUTPUTOFFSET_Msk 0x1FFFFUL
/* MXNNLITE_1_0.OUTSTREAMERSCALINGFACTOR */
#define MXNNLITE_1_0_OUTSTREAMERSCALINGFACTOR_OUTSTREAMERSCALINGFACTOR_Pos 0UL
#define MXNNLITE_1_0_OUTSTREAMERSCALINGFACTOR_OUTSTREAMERSCALINGFACTOR_Msk 0xFFFFFFFFUL
/* MXNNLITE_1_0.OUTSTREAMERCLIPPINGMASK */
#define MXNNLITE_1_0_OUTSTREAMERCLIPPINGMASK_OUTSTREAMERCLIPPINGMASK_Pos 0UL
#define MXNNLITE_1_0_OUTSTREAMERCLIPPINGMASK_OUTSTREAMERCLIPPINGMASK_Msk 0xFFFFFFFFUL
/* MXNNLITE_1_0.BIASBASEADDR */
#define MXNNLITE_1_0_BIASBASEADDR_BIASBASEADDR_Pos 0UL
#define MXNNLITE_1_0_BIASBASEADDR_BIASBASEADDR_Msk 0xFFFFFFFFUL
/* MXNNLITE_1_0.STREAMERMODES */
#define MXNNLITE_1_0_STREAMERMODES_WEIGHTSTREAMERSIGNEDVALUES_Pos 0UL
#define MXNNLITE_1_0_STREAMERMODES_WEIGHTSTREAMERSIGNEDVALUES_Msk 0x1UL
#define MXNNLITE_1_0_STREAMERMODES_ACTIVATIONSTREAMERSIGNEDVALUES_Pos 1UL
#define MXNNLITE_1_0_STREAMERMODES_ACTIVATIONSTREAMERSIGNEDVALUES_Msk 0x2UL
#define MXNNLITE_1_0_STREAMERMODES_OUTSTREAMERSIGNEDVALUES_Pos 2UL
#define MXNNLITE_1_0_STREAMERMODES_OUTSTREAMERSIGNEDVALUES_Msk 0x4UL
#define MXNNLITE_1_0_STREAMERMODES_ACTIVATIONSTREAMERSPARSEEN_Pos 3UL
#define MXNNLITE_1_0_STREAMERMODES_ACTIVATIONSTREAMERSPARSEEN_Msk 0x8UL
#define MXNNLITE_1_0_STREAMERMODES_BIASEN_Pos   8UL
#define MXNNLITE_1_0_STREAMERMODES_BIASEN_Msk   0x100UL
/* MXNNLITE_1_0.NONZEROWEIGHTSPOINTER */
#define MXNNLITE_1_0_NONZEROWEIGHTSPOINTER_NONZEROWEIGHTSPOINTER_Pos 0UL
#define MXNNLITE_1_0_NONZEROWEIGHTSPOINTER_NONZEROWEIGHTSPOINTER_Msk 0xFFFFFFFFUL
/* MXNNLITE_1_0.OUTPUTWIDTH */
#define MXNNLITE_1_0_OUTPUTWIDTH_OUTPUTWIDTH_Pos 0UL
#define MXNNLITE_1_0_OUTPUTWIDTH_OUTPUTWIDTH_Msk 0x1FFFFUL
/* MXNNLITE_1_0.OUTPUTHEIGHT */
#define MXNNLITE_1_0_OUTPUTHEIGHT_OUTPUTHEIGHT_Pos 0UL
#define MXNNLITE_1_0_OUTPUTHEIGHT_OUTPUTHEIGHT_Msk 0x1FFFFUL
/* MXNNLITE_1_0.STRIDE */
#define MXNNLITE_1_0_STRIDE_STRIDECHANNELTIMESCOLUMN_Pos 0UL
#define MXNNLITE_1_0_STRIDE_STRIDECHANNELTIMESCOLUMN_Msk 0xFFFFUL
#define MXNNLITE_1_0_STRIDE_STRIDEROW_Pos       16UL
#define MXNNLITE_1_0_STRIDE_STRIDEROW_Msk       0xFF0000UL
/* MXNNLITE_1_0.INTERPOLATIONLUTADDR */
#define MXNNLITE_1_0_INTERPOLATIONLUTADDR_INTERPOLATIONLUTADDR_Pos 0UL
#define MXNNLITE_1_0_INTERPOLATIONLUTADDR_INTERPOLATIONLUTADDR_Msk 0x1UL
/* MXNNLITE_1_0.INTERPOLATIONLUTWDATA */
#define MXNNLITE_1_0_INTERPOLATIONLUTWDATA_INTERPOLATIONYINTERCEPT_Pos 0UL
#define MXNNLITE_1_0_INTERPOLATIONLUTWDATA_INTERPOLATIONYINTERCEPT_Msk 0xFFFFUL
#define MXNNLITE_1_0_INTERPOLATIONLUTWDATA_INTERPOLATIONSLOPE_Pos 16UL
#define MXNNLITE_1_0_INTERPOLATIONLUTWDATA_INTERPOLATIONSLOPE_Msk 0xFFFF0000UL
/* MXNNLITE_1_0.NNLAYER_ACTIVATION_TYPE_CTL */
#define MXNNLITE_1_0_NNLAYER_ACTIVATION_TYPE_CTL_NNLAYER_TYPE_CTL_Pos 0UL
#define MXNNLITE_1_0_NNLAYER_ACTIVATION_TYPE_CTL_NNLAYER_TYPE_CTL_Msk 0x1UL
#define MXNNLITE_1_0_NNLAYER_ACTIVATION_TYPE_CTL_ACTIVATION_FUNC_EN_Pos 2UL
#define MXNNLITE_1_0_NNLAYER_ACTIVATION_TYPE_CTL_ACTIVATION_FUNC_EN_Msk 0x4UL
#define MXNNLITE_1_0_NNLAYER_ACTIVATION_TYPE_CTL_ACTIVATION_SIZE_CTL_Pos 4UL
#define MXNNLITE_1_0_NNLAYER_ACTIVATION_TYPE_CTL_ACTIVATION_SIZE_CTL_Msk 0x10UL
/* MXNNLITE_1_0.INTR */
#define MXNNLITE_1_0_INTR_INTR_DONE_Pos         0UL
#define MXNNLITE_1_0_INTR_INTR_DONE_Msk         0x1UL
#define MXNNLITE_1_0_INTR_INTR_MEM_ERR_SPARSITY_Pos 1UL
#define MXNNLITE_1_0_INTR_INTR_MEM_ERR_SPARSITY_Msk 0x2UL
#define MXNNLITE_1_0_INTR_INTR_MEM_ERR_ACTIVATIONSTREAMER_Pos 2UL
#define MXNNLITE_1_0_INTR_INTR_MEM_ERR_ACTIVATIONSTREAMER_Msk 0x4UL
#define MXNNLITE_1_0_INTR_INTR_MEM_ERR_WEIGHTSTREAMER_Pos 3UL
#define MXNNLITE_1_0_INTR_INTR_MEM_ERR_WEIGHTSTREAMER_Msk 0x8UL
#define MXNNLITE_1_0_INTR_INTR_MEM_ERR_BIASSTREAMER_Pos 4UL
#define MXNNLITE_1_0_INTR_INTR_MEM_ERR_BIASSTREAMER_Msk 0x10UL
#define MXNNLITE_1_0_INTR_INTR_MEM_ERR_OUTPUTSTREAMER_Pos 5UL
#define MXNNLITE_1_0_INTR_INTR_MEM_ERR_OUTPUTSTREAMER_Msk 0x20UL
#define MXNNLITE_1_0_INTR_INTR_SATURATION_Pos   6UL
#define MXNNLITE_1_0_INTR_INTR_SATURATION_Msk   0x40UL
/* MXNNLITE_1_0.INTR_SET */
#define MXNNLITE_1_0_INTR_SET_INTR_SET_DONE_Pos 0UL
#define MXNNLITE_1_0_INTR_SET_INTR_SET_DONE_Msk 0x1UL
#define MXNNLITE_1_0_INTR_SET_INTR_SET_MEM_ERR_SPARSITY_Pos 1UL
#define MXNNLITE_1_0_INTR_SET_INTR_SET_MEM_ERR_SPARSITY_Msk 0x2UL
#define MXNNLITE_1_0_INTR_SET_INTR_SET_MEM_ERR_ACTIVATIONSTREAMER_Pos 2UL
#define MXNNLITE_1_0_INTR_SET_INTR_SET_MEM_ERR_ACTIVATIONSTREAMER_Msk 0x4UL
#define MXNNLITE_1_0_INTR_SET_INTR_SET_MEM_ERR_WEIGHTSTREAMER_Pos 3UL
#define MXNNLITE_1_0_INTR_SET_INTR_SET_MEM_ERR_WEIGHTSTREAMER_Msk 0x8UL
#define MXNNLITE_1_0_INTR_SET_INTR_SET_MEM_ERR_BIASSTREAMER_Pos 4UL
#define MXNNLITE_1_0_INTR_SET_INTR_SET_MEM_ERR_BIASSTREAMER_Msk 0x10UL
#define MXNNLITE_1_0_INTR_SET_INTR_SET_MEM_ERR_OUTPUTSTREAMER_Pos 5UL
#define MXNNLITE_1_0_INTR_SET_INTR_SET_MEM_ERR_OUTPUTSTREAMER_Msk 0x20UL
#define MXNNLITE_1_0_INTR_SET_INTR_SET_SATURATION_Pos 6UL
#define MXNNLITE_1_0_INTR_SET_INTR_SET_SATURATION_Msk 0x40UL
/* MXNNLITE_1_0.INTR_MASK */
#define MXNNLITE_1_0_INTR_MASK_INTR_MASK_DONE_Pos 0UL
#define MXNNLITE_1_0_INTR_MASK_INTR_MASK_DONE_Msk 0x1UL
#define MXNNLITE_1_0_INTR_MASK_INTR_MASK_MEM_ERR_SPARSITY_Pos 1UL
#define MXNNLITE_1_0_INTR_MASK_INTR_MASK_MEM_ERR_SPARSITY_Msk 0x2UL
#define MXNNLITE_1_0_INTR_MASK_INTR_MASK_MEM_ERR_ACTIVATIONSTREAMER_Pos 2UL
#define MXNNLITE_1_0_INTR_MASK_INTR_MASK_MEM_ERR_ACTIVATIONSTREAMER_Msk 0x4UL
#define MXNNLITE_1_0_INTR_MASK_INTR_MASK_MEM_ERR_WEIGHTSTREAMER_Pos 3UL
#define MXNNLITE_1_0_INTR_MASK_INTR_MASK_MEM_ERR_WEIGHTSTREAMER_Msk 0x8UL
#define MXNNLITE_1_0_INTR_MASK_INTR_MASK_MEM_ERR_BIASSTREAMER_Pos 4UL
#define MXNNLITE_1_0_INTR_MASK_INTR_MASK_MEM_ERR_BIASSTREAMER_Msk 0x10UL
#define MXNNLITE_1_0_INTR_MASK_INTR_MASK_MEM_ERR_OUTPUTSTREAMER_Pos 5UL
#define MXNNLITE_1_0_INTR_MASK_INTR_MASK_MEM_ERR_OUTPUTSTREAMER_Msk 0x20UL
#define MXNNLITE_1_0_INTR_MASK_INTR_MASK_SATURATION_Pos 6UL
#define MXNNLITE_1_0_INTR_MASK_INTR_MASK_SATURATION_Msk 0x40UL
/* MXNNLITE_1_0.TRIG_MASK */
#define MXNNLITE_1_0_TRIG_MASK_TRIG_MASK_DONE_Pos 0UL
#define MXNNLITE_1_0_TRIG_MASK_TRIG_MASK_DONE_Msk 0x1UL
/* MXNNLITE_1_0.CMD */
#define MXNNLITE_1_0_CMD_START_CMD_Pos          0UL
#define MXNNLITE_1_0_CMD_START_CMD_Msk          0x1UL
#define MXNNLITE_1_0_CMD_ABORT_CMD_Pos          1UL
#define MXNNLITE_1_0_CMD_ABORT_CMD_Msk          0x2UL
/* MXNNLITE_1_0.INTR_MASKED */
#define MXNNLITE_1_0_INTR_MASKED_INTR_MASKED_DONE_Pos 0UL
#define MXNNLITE_1_0_INTR_MASKED_INTR_MASKED_DONE_Msk 0x1UL
#define MXNNLITE_1_0_INTR_MASKED_INTR_MASKED_MEM_ERR_SPARSITY_Pos 1UL
#define MXNNLITE_1_0_INTR_MASKED_INTR_MASKED_MEM_ERR_SPARSITY_Msk 0x2UL
#define MXNNLITE_1_0_INTR_MASKED_INTR_MASKED_MEM_ERR_ACTIVATIONSTREAMER_Pos 2UL
#define MXNNLITE_1_0_INTR_MASKED_INTR_MASKED_MEM_ERR_ACTIVATIONSTREAMER_Msk 0x4UL
#define MXNNLITE_1_0_INTR_MASKED_INTR_MASKED_MEM_ERR_WEIGHTSTREAMER_Pos 3UL
#define MXNNLITE_1_0_INTR_MASKED_INTR_MASKED_MEM_ERR_WEIGHTSTREAMER_Msk 0x8UL
#define MXNNLITE_1_0_INTR_MASKED_INTR_MASKED_MEM_ERR_BIASSTREAMER_Pos 4UL
#define MXNNLITE_1_0_INTR_MASKED_INTR_MASKED_MEM_ERR_BIASSTREAMER_Msk 0x10UL
#define MXNNLITE_1_0_INTR_MASKED_INTR_MASKED_MEM_ERR_OUTPUTSTREAMER_Pos 5UL
#define MXNNLITE_1_0_INTR_MASKED_INTR_MASKED_MEM_ERR_OUTPUTSTREAMER_Msk 0x20UL
#define MXNNLITE_1_0_INTR_MASKED_INTR_MASKED_SATURATION_Pos 6UL
#define MXNNLITE_1_0_INTR_MASKED_INTR_MASKED_SATURATION_Msk 0x40UL
/* MXNNLITE_1_0.STATUS */
#define MXNNLITE_1_0_STATUS_BUSY_STATUS_Pos     0UL
#define MXNNLITE_1_0_STATUS_BUSY_STATUS_Msk     0x1UL
#define MXNNLITE_1_0_STATUS_ACTIVATIONSTREAMERDONE_Pos 1UL
#define MXNNLITE_1_0_STATUS_ACTIVATIONSTREAMERDONE_Msk 0x2UL


#endif /* _CYIP_MXNNLITE_1_0_H_ */


/* [] END OF FILE */
