/***************************************************************************//**
* \file cyhal_triggers_psc3.c
*
* \brief
* PSC3 family HAL triggers header
*
********************************************************************************
* \copyright
* (c) (2016-2024), Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
*
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cy_device_headers.h"
#include "cyhal_hw_types.h"

#ifdef CY_DEVICE_PSC3
#include "triggers/cyhal_triggers_psc3.h"

const uint16_t cyhal_sources_per_mux[18] =
{
    128, 128, 198, 9, 9, 9, 177, 3, 4, 23, 132, 51, 21, 99, 79, 2, 20, 8, 
};

const bool cyhal_is_mux_1to1[18] =
{
    false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, 
};

const _cyhal_trigger_source_psc3_t cyhal_mux0_sources[128] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT3,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT00,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT01,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT02,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT03,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0256,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0257,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0258,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0259,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0260,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0261,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0262,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0263,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0512,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0513,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0514,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0515,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0516,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0517,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0518,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0519,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN28,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN29,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN30,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN31,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN32,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN33,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN34,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN35,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN36,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN37,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN38,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN39,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN40,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN41,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN42,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN43,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN44,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN45,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN46,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN47,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN48,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN49,
    _CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB0_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB0_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB1_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB2_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB3_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB4_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB5_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_RX_REQ,
    _CYHAL_TRIGGER_DEBUG600_CTI_TR_OUT0,
    _CYHAL_TRIGGER_DEBUG600_CTI_TR_OUT1,
    _CYHAL_TRIGGER_CORDIC0_TR_DONE_MXCORDIC,
    _CYHAL_TRIGGER_CANFD0_TR_TMP_RTP_OUT0,
    _CYHAL_TRIGGER_CANFD0_TR_TMP_RTP_OUT1,
    _CYHAL_TRIGGER_CANFD0_TR_DBG_DMA_REQ0,
    _CYHAL_TRIGGER_CANFD0_TR_DBG_DMA_REQ1,
    _CYHAL_TRIGGER_CANFD0_TR_FIFO00,
    _CYHAL_TRIGGER_CANFD0_TR_FIFO01,
    _CYHAL_TRIGGER_CANFD0_TR_FIFO10,
    _CYHAL_TRIGGER_CANFD0_TR_FIFO11,
    _CYHAL_TRIGGER_LPCOMP_DSI_COMP0,
    _CYHAL_TRIGGER_LPCOMP_DSI_COMP1,
    _CYHAL_TRIGGER_CPUSS_TR_FAULT0,
    _CYHAL_TRIGGER_CRYPTOLITE_TR_TRNG_BITSTREAM,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT0,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT1,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT2,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT3,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT4,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT5,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT6,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT7,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT4,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT5,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT6,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT7,
};

const _cyhal_trigger_source_psc3_t cyhal_mux1_sources[128] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT3,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT00,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT01,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT02,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT03,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0256,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0257,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0258,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0259,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0260,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0261,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0262,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0263,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0512,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0513,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0514,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0515,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0516,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0517,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0518,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0519,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN28,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN29,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN30,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN31,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN32,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN33,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN34,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN35,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN36,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN37,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN38,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN39,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN40,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN41,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN42,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN43,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN44,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN45,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN46,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN47,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN48,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN49,
    _CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB0_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB0_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB1_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB2_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB3_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB4_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB5_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_RX_REQ,
    _CYHAL_TRIGGER_DEBUG600_CTI_TR_OUT0,
    _CYHAL_TRIGGER_DEBUG600_CTI_TR_OUT1,
    _CYHAL_TRIGGER_CORDIC0_TR_DONE_MXCORDIC,
    _CYHAL_TRIGGER_CANFD0_TR_TMP_RTP_OUT0,
    _CYHAL_TRIGGER_CANFD0_TR_TMP_RTP_OUT1,
    _CYHAL_TRIGGER_CANFD0_TR_DBG_DMA_REQ0,
    _CYHAL_TRIGGER_CANFD0_TR_DBG_DMA_REQ1,
    _CYHAL_TRIGGER_CANFD0_TR_FIFO00,
    _CYHAL_TRIGGER_CANFD0_TR_FIFO01,
    _CYHAL_TRIGGER_CANFD0_TR_FIFO10,
    _CYHAL_TRIGGER_CANFD0_TR_FIFO11,
    _CYHAL_TRIGGER_LPCOMP_DSI_COMP0,
    _CYHAL_TRIGGER_LPCOMP_DSI_COMP1,
    _CYHAL_TRIGGER_CPUSS_TR_FAULT0,
    _CYHAL_TRIGGER_CRYPTOLITE_TR_TRNG_BITSTREAM,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT0,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT1,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT2,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT3,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT4,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT5,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT6,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT7,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT4,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT5,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT6,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT7,
};

const _cyhal_trigger_source_psc3_t cyhal_mux2_sources[198] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT7,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT8,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT9,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT10,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT11,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT12,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT13,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT14,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT15,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT7,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT8,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT9,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT10,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT11,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT12,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT13,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT14,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT15,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT10,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT11,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT12,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT13,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1256,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1257,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1258,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1259,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1260,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1261,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1262,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1263,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1512,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1513,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1514,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1515,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1516,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1517,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1518,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1519,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT256,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT257,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT258,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT259,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT260,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT261,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT262,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT263,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE0,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE1,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE2,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE3,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL0,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL1,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL2,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL3,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE256,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE257,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE258,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE259,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE260,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE261,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE262,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE263,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL256,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL257,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL258,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL259,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL260,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL261,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL262,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL263,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE512,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE513,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE514,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE515,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE516,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE517,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE518,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE519,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL512,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL513,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL514,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL515,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL516,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL517,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL518,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL519,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN28,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN29,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN30,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN31,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN32,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN33,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN34,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN35,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN36,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN37,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN38,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN39,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN40,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN41,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN42,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN43,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN44,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN45,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN46,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN47,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN48,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN49,
    _CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB0_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB0_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB1_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB2_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB3_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB4_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB5_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_RX_REQ,
    _CYHAL_TRIGGER_DEBUG600_CTI_TR_OUT0,
    _CYHAL_TRIGGER_DEBUG600_CTI_TR_OUT1,
    _CYHAL_TRIGGER_CORDIC0_TR_DONE_MXCORDIC,
    _CYHAL_TRIGGER_CANFD0_TR_TMP_RTP_OUT0,
    _CYHAL_TRIGGER_CANFD0_TR_TMP_RTP_OUT1,
    _CYHAL_TRIGGER_LPCOMP_DSI_COMP0,
    _CYHAL_TRIGGER_LPCOMP_DSI_COMP1,
    _CYHAL_TRIGGER_CPUSS_TR_FAULT0,
    _CYHAL_TRIGGER_CRYPTOLITE_TR_TRNG_BITSTREAM,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT0,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT1,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT2,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT3,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT4,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT5,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT6,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT7,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT4,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT5,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT6,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT7,
};

const _cyhal_trigger_source_psc3_t cyhal_mux3_sources[9] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE0,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE1,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE2,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE3,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL0,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL1,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL2,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL3,
};

const _cyhal_trigger_source_psc3_t cyhal_mux4_sources[9] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE256,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE257,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE258,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE259,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL256,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL257,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL258,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL259,
};

const _cyhal_trigger_source_psc3_t cyhal_mux5_sources[9] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE512,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE513,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE514,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE515,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL512,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL513,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL514,
    _CYHAL_TRIGGER_TCPWM0_TR_LINE_COMPL515,
};

const _cyhal_trigger_source_psc3_t cyhal_mux6_sources[177] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT7,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT8,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT9,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT10,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT11,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT12,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT13,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT14,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT15,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT7,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT8,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT9,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT10,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT11,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT12,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT13,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT14,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT15,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT00,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT10,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT01,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT11,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT02,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT12,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT03,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT13,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0256,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1256,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0257,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1257,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0258,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1258,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0259,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1259,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0260,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1260,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0261,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1261,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0262,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1262,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0263,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1263,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0512,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1512,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0513,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1513,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0514,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1514,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0515,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1515,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0516,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1516,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0517,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1517,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0518,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1518,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0519,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1519,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT256,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT257,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT258,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT259,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT260,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT261,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT262,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT263,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN28,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN29,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN30,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN31,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN32,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN33,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN34,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN35,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN36,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN37,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN38,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN39,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN40,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN41,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN42,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN43,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN44,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN45,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN46,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN47,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN48,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN49,
    _CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB0_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB0_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB1_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB2_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB3_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB4_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB5_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_RX_REQ,
    _CYHAL_TRIGGER_DEBUG600_CTI_TR_OUT0,
    _CYHAL_TRIGGER_DEBUG600_CTI_TR_OUT1,
    _CYHAL_TRIGGER_CORDIC0_TR_DONE_MXCORDIC,
    _CYHAL_TRIGGER_CANFD0_TR_TMP_RTP_OUT0,
    _CYHAL_TRIGGER_CANFD0_TR_TMP_RTP_OUT1,
    _CYHAL_TRIGGER_LPCOMP_DSI_COMP0,
    _CYHAL_TRIGGER_LPCOMP_DSI_COMP1,
    _CYHAL_TRIGGER_CPUSS_TR_FAULT0,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT0,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT1,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT2,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT3,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT4,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT5,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT6,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT7,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT4,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT5,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT6,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT7,
};

const _cyhal_trigger_source_psc3_t cyhal_mux7_sources[3] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CANFD0_TR_TMP_RTP_OUT0,
    _CYHAL_TRIGGER_CANFD0_TR_TMP_RTP_OUT1,
};

const _cyhal_trigger_source_psc3_t cyhal_mux8_sources[4] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_TR_FAULT0,
    _CYHAL_TRIGGER_DEBUG600_CTI_TR_OUT0,
    _CYHAL_TRIGGER_DEBUG600_CTI_TR_OUT1,
};

const _cyhal_trigger_source_psc3_t cyhal_mux9_sources[23] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_LPCOMP_DSI_COMP0,
    _CYHAL_TRIGGER_LPCOMP_DSI_COMP1,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_FIFO_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT0,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT1,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT2,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT3,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT4,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT5,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT6,
    _CYHAL_TRIGGER_PASS_TR_PULSE_OUT7,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT4,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT5,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT6,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT7,
};

const _cyhal_trigger_source_psc3_t cyhal_mux10_sources[132] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT7,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT8,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT9,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT10,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT11,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT12,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT13,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT14,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT15,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT0,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT1,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT2,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT3,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT4,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT5,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT7,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT8,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT9,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT10,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT11,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT12,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT13,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT14,
    _CYHAL_TRIGGER_CPUSS_DW1_TR_OUT15,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT10,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT11,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT12,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT13,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1256,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1257,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1258,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1259,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1260,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1261,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1262,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1263,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1512,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1513,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1514,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1515,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1516,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1517,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1518,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1519,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT256,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT257,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT258,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT259,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT260,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT261,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT262,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT263,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN28,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN29,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN30,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN31,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN32,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN33,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN34,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN35,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN36,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN37,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN38,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN39,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN40,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN41,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN42,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN43,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN44,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN45,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN46,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN47,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN48,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN49,
    _CYHAL_TRIGGER_SCB0_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB0_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB0_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB1_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB1_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB2_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB2_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB3_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB3_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB4_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB4_TR_RX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_I2C_SCL_FILTERED,
    _CYHAL_TRIGGER_SCB5_TR_TX_REQ,
    _CYHAL_TRIGGER_SCB5_TR_RX_REQ,
    _CYHAL_TRIGGER_CANFD0_TR_TMP_RTP_OUT0,
    _CYHAL_TRIGGER_CANFD0_TR_TMP_RTP_OUT1,
    _CYHAL_TRIGGER_CPUSS_TR_FAULT0,
};

const _cyhal_trigger_source_psc3_t cyhal_mux11_sources[51] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN28,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN29,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN30,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN31,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN32,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN33,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN34,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN35,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN36,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN37,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN38,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN39,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN40,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN41,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN42,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN43,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN44,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN45,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN46,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN47,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN48,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN49,
};

const _cyhal_trigger_source_psc3_t cyhal_mux12_sources[21] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT00,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT01,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT02,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT03,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0256,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0257,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0258,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0259,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0260,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0261,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0262,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0263,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0512,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0513,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0514,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0515,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0516,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0517,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0518,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0519,
};

const _cyhal_trigger_source_psc3_t cyhal_mux13_sources[99] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT00,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT10,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT01,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT11,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT02,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT12,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT03,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT13,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0256,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1256,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0257,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1257,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0258,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1258,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0259,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1259,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0260,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1260,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0261,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1261,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0262,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1262,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0263,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1263,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0512,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1512,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0513,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1513,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0514,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1514,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0515,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1515,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0516,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1516,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0517,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1517,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0518,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1518,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT0519,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1519,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN28,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN29,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN30,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN31,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN32,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN33,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN34,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN35,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN36,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN37,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN38,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN39,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN40,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN41,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN42,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN43,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN44,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN45,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN46,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN47,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN48,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN49,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT4,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT5,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT6,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT7,
};

const _cyhal_trigger_source_psc3_t cyhal_mux14_sources[79] =
{
    _CYHAL_TRIGGER_CPUSS_ZERO,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT10,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT11,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT12,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT13,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1256,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1257,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1258,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1259,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1260,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1261,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1262,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1263,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1512,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1513,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1514,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1515,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1516,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1517,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1518,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1519,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT256,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT257,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT258,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT259,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT260,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT261,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT262,
    _CYHAL_TRIGGER_TCPWM0_TR_MOTIF_OUT263,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN0,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN1,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN2,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN3,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN4,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN5,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN6,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN7,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN8,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN9,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN10,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN11,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN12,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN13,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN14,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN15,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN16,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN17,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN18,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN19,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN20,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN21,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN22,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN23,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN24,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN25,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN26,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN27,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN28,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN29,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN30,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN31,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN32,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN33,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN34,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN35,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN36,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN37,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN38,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN39,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN40,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN41,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN42,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN43,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN44,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN45,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN46,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN47,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN48,
    _CYHAL_TRIGGER_IOSS_PERI_TR_IO_INPUT_IN49,
};

const _cyhal_trigger_source_psc3_t cyhal_mux15_sources[2] =
{
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT6,
    _CYHAL_TRIGGER_CPUSS_DW0_TR_OUT8,
};

const _cyhal_trigger_source_psc3_t cyhal_mux16_sources[20] =
{
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT0,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT1,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT2,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT3,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT4,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT4,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT4,
    _CYHAL_TRIGGER_PASS_TR_LEVEL_OUT4,
};

const _cyhal_trigger_source_psc3_t cyhal_mux17_sources[8] =
{
    _CYHAL_TRIGGER_TCPWM0_TR_OUT12,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT13,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1261,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1262,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1263,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1517,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1518,
    _CYHAL_TRIGGER_TCPWM0_TR_OUT1519,
};

const _cyhal_trigger_source_psc3_t* cyhal_mux_to_sources[18] =
{
    cyhal_mux0_sources,
    cyhal_mux1_sources,
    cyhal_mux2_sources,
    cyhal_mux3_sources,
    cyhal_mux4_sources,
    cyhal_mux5_sources,
    cyhal_mux6_sources,
    cyhal_mux7_sources,
    cyhal_mux8_sources,
    cyhal_mux9_sources,
    cyhal_mux10_sources,
    cyhal_mux11_sources,
    cyhal_mux12_sources,
    cyhal_mux13_sources,
    cyhal_mux14_sources,
    cyhal_mux15_sources,
    cyhal_mux16_sources,
    cyhal_mux17_sources,
};

const uint8_t cyhal_dest_to_mux[214] =
{
    128, /* CYHAL_TRIGGER_CANFD0_TR_DBG_DMA_ACK0 */
    128, /* CYHAL_TRIGGER_CANFD0_TR_DBG_DMA_ACK1 */
    7, /* CYHAL_TRIGGER_CANFD0_TR_EVT_SWT_IN0 */
    7, /* CYHAL_TRIGGER_CANFD0_TR_EVT_SWT_IN1 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN0 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN1 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN2 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN3 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN4 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN5 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN6 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN7 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN8 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN9 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN10 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN11 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN12 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN13 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN14 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN15 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN0 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN1 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN2 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN3 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN4 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN5 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN6 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN7 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN8 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN9 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN10 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN11 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN12 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN13 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN14 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN15 */
    6, /* CYHAL_TRIGGER_DEBUG600_CTI_TR_IN0 */
    6, /* CYHAL_TRIGGER_DEBUG600_CTI_TR_IN1 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT0 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT1 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT2 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT3 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT4 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT5 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT6 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT7 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT8 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT9 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT10 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT11 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT12 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT13 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT14 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT15 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT16 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT17 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT18 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT19 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT20 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT21 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT22 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT23 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT24 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT25 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT26 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT27 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT28 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT29 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT30 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT31 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT32 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT33 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT34 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT35 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT36 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT37 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT38 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT39 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT40 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT41 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT42 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT43 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT44 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT45 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT46 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT47 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT48 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT49 */
    3, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT50 */
    3, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT51 */
    3, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT52 */
    3, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT53 */
    3, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT54 */
    3, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT55 */
    3, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT56 */
    3, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT57 */
    4, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT58 */
    4, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT59 */
    4, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT60 */
    4, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT61 */
    4, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT62 */
    4, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT63 */
    4, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT64 */
    4, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT65 */
    5, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT66 */
    5, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT67 */
    5, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT68 */
    5, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT69 */
    5, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT70 */
    5, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT71 */
    5, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT72 */
    5, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT73 */
    14, /* CYHAL_TRIGGER_PASS_TR_A_IN0 */
    14, /* CYHAL_TRIGGER_PASS_TR_A_IN1 */
    14, /* CYHAL_TRIGGER_PASS_TR_A_IN2 */
    14, /* CYHAL_TRIGGER_PASS_TR_A_IN3 */
    14, /* CYHAL_TRIGGER_PASS_TR_A_IN4 */
    14, /* CYHAL_TRIGGER_PASS_TR_A_IN5 */
    14, /* CYHAL_TRIGGER_PASS_TR_A_IN6 */
    14, /* CYHAL_TRIGGER_PASS_TR_A_IN7 */
    130, /* CYHAL_TRIGGER_PASS_TR_B_IN0 */
    130, /* CYHAL_TRIGGER_PASS_TR_B_IN1 */
    130, /* CYHAL_TRIGGER_PASS_TR_B_IN2 */
    130, /* CYHAL_TRIGGER_PASS_TR_B_IN3 */
    130, /* CYHAL_TRIGGER_PASS_TR_B_IN4 */
    130, /* CYHAL_TRIGGER_PASS_TR_B_IN5 */
    130, /* CYHAL_TRIGGER_PASS_TR_B_IN6 */
    130, /* CYHAL_TRIGGER_PASS_TR_B_IN7 */
    8, /* CYHAL_TRIGGER_PERI_TR_DBG_FREEZE */
    9, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN0 */
    9, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN1 */
    9, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN2 */
    9, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN3 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN4 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN5 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN6 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN7 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN8 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN9 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN10 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN11 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN12 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN13 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN14 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN15 */
    8, /* CYHAL_TRIGGER_TCPWM0_TR_DEBUG_FREEZE */
    13, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN256 */
    13, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN257 */
    13, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN258 */
    13, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN259 */
    13, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN260 */
    13, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN261 */
    13, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN262 */
    13, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN263 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN0 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN2 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN3 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN4 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN5 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN6 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN7 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN8 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN9 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN10 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN11 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1536 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1537 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1538 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1539 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1540 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1541 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1542 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1543 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1544 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1545 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1546 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1547 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1548 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1549 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1550 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1551 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1552 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1553 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1554 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1555 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1556 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1557 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1558 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1559 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN768 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN769 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN770 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN771 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN772 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN773 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN774 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN775 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN776 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN777 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN778 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN779 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN780 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN781 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN782 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN783 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN784 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN785 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN786 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN787 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN788 */
    129, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN789 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN790 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN791 */
};

const uint8_t cyhal_mux_dest_index[214] =
{
    0, /* CYHAL_TRIGGER_CANFD0_TR_DBG_DMA_ACK0 */
    1, /* CYHAL_TRIGGER_CANFD0_TR_DBG_DMA_ACK1 */
    0, /* CYHAL_TRIGGER_CANFD0_TR_EVT_SWT_IN0 */
    1, /* CYHAL_TRIGGER_CANFD0_TR_EVT_SWT_IN1 */
    0, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN0 */
    1, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN1 */
    2, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN2 */
    3, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN3 */
    4, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN4 */
    5, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN5 */
    6, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN6 */
    7, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN7 */
    8, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN8 */
    9, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN9 */
    10, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN10 */
    11, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN11 */
    12, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN12 */
    13, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN13 */
    14, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN14 */
    15, /* CYHAL_TRIGGER_CPUSS_DW0_TR_IN15 */
    0, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN0 */
    1, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN1 */
    2, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN2 */
    3, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN3 */
    4, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN4 */
    5, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN5 */
    6, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN6 */
    7, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN7 */
    8, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN8 */
    9, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN9 */
    10, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN10 */
    11, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN11 */
    12, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN12 */
    13, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN13 */
    14, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN14 */
    15, /* CYHAL_TRIGGER_CPUSS_DW1_TR_IN15 */
    0, /* CYHAL_TRIGGER_DEBUG600_CTI_TR_IN0 */
    1, /* CYHAL_TRIGGER_DEBUG600_CTI_TR_IN1 */
    0, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT0 */
    1, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT1 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT2 */
    3, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT3 */
    4, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT4 */
    5, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT5 */
    6, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT6 */
    7, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT7 */
    8, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT8 */
    9, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT9 */
    10, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT10 */
    11, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT11 */
    12, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT12 */
    13, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT13 */
    14, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT14 */
    15, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT15 */
    16, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT16 */
    17, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT17 */
    18, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT18 */
    19, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT19 */
    20, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT20 */
    21, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT21 */
    22, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT22 */
    23, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT23 */
    24, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT24 */
    25, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT25 */
    26, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT26 */
    27, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT27 */
    28, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT28 */
    29, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT29 */
    30, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT30 */
    31, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT31 */
    32, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT32 */
    33, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT33 */
    34, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT34 */
    35, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT35 */
    36, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT36 */
    37, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT37 */
    38, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT38 */
    39, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT39 */
    40, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT40 */
    41, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT41 */
    42, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT42 */
    43, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT43 */
    44, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT44 */
    45, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT45 */
    46, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT46 */
    47, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT47 */
    48, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT48 */
    49, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT49 */
    0, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT50 */
    1, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT51 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT52 */
    3, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT53 */
    4, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT54 */
    5, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT55 */
    6, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT56 */
    7, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT57 */
    0, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT58 */
    1, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT59 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT60 */
    3, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT61 */
    4, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT62 */
    5, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT63 */
    6, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT64 */
    7, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT65 */
    0, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT66 */
    1, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT67 */
    2, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT68 */
    3, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT69 */
    4, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT70 */
    5, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT71 */
    6, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT72 */
    7, /* CYHAL_TRIGGER_IOSS_PERI_TR_IO_OUTPUT_OUT73 */
    0, /* CYHAL_TRIGGER_PASS_TR_A_IN0 */
    1, /* CYHAL_TRIGGER_PASS_TR_A_IN1 */
    2, /* CYHAL_TRIGGER_PASS_TR_A_IN2 */
    3, /* CYHAL_TRIGGER_PASS_TR_A_IN3 */
    4, /* CYHAL_TRIGGER_PASS_TR_A_IN4 */
    5, /* CYHAL_TRIGGER_PASS_TR_A_IN5 */
    6, /* CYHAL_TRIGGER_PASS_TR_A_IN6 */
    7, /* CYHAL_TRIGGER_PASS_TR_A_IN7 */
    0, /* CYHAL_TRIGGER_PASS_TR_B_IN0 */
    1, /* CYHAL_TRIGGER_PASS_TR_B_IN1 */
    2, /* CYHAL_TRIGGER_PASS_TR_B_IN2 */
    3, /* CYHAL_TRIGGER_PASS_TR_B_IN3 */
    4, /* CYHAL_TRIGGER_PASS_TR_B_IN4 */
    5, /* CYHAL_TRIGGER_PASS_TR_B_IN5 */
    6, /* CYHAL_TRIGGER_PASS_TR_B_IN6 */
    7, /* CYHAL_TRIGGER_PASS_TR_B_IN7 */
    0, /* CYHAL_TRIGGER_PERI_TR_DBG_FREEZE */
    0, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN0 */
    1, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN1 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN2 */
    3, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN3 */
    0, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN4 */
    1, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN5 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN6 */
    3, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN7 */
    4, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN8 */
    5, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN9 */
    6, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN10 */
    7, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN11 */
    8, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN12 */
    9, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN13 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN14 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ALL_CNT_IN15 */
    1, /* CYHAL_TRIGGER_TCPWM0_TR_DEBUG_FREEZE */
    0, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN256 */
    1, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN257 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN258 */
    3, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN259 */
    4, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN260 */
    5, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN261 */
    6, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN262 */
    7, /* CYHAL_TRIGGER_TCPWM0_TR_MOTIF_IN263 */
    0, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN0 */
    0, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1 */
    0, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN2 */
    4, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN3 */
    1, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN4 */
    1, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN5 */
    8, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN6 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN7 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN8 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN9 */
    3, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN10 */
    3, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN11 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1536 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1537 */
    12, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1538 */
    13, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1539 */
    13, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1540 */
    13, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1541 */
    14, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1542 */
    14, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1543 */
    14, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1544 */
    15, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1545 */
    15, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1546 */
    15, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1547 */
    16, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1548 */
    16, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1549 */
    16, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1550 */
    17, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1551 */
    17, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1552 */
    17, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1553 */
    18, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1554 */
    18, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1555 */
    18, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1556 */
    19, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1557 */
    19, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1558 */
    19, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN1559 */
    1, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN768 */
    4, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN769 */
    4, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN770 */
    2, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN771 */
    5, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN772 */
    5, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN773 */
    3, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN774 */
    6, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN775 */
    6, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN776 */
    5, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN777 */
    7, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN778 */
    7, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN779 */
    6, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN780 */
    8, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN781 */
    8, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN782 */
    7, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN783 */
    9, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN784 */
    9, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN785 */
    9, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN786 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN787 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN788 */
    10, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN789 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN790 */
    11, /* CYHAL_TRIGGER_TCPWM0_TR_ONE_CNT_IN791 */
};

#endif /* CY_DEVICE_PSC3 */
