################################################################################
# \file bsp.mk
#
# \brief
# Define the BSP for the PSOC Edge E84 MCU
#
################################################################################
# \copyright
# Copyright 2023-2025 Cypress Semiconductor Corporation (an Infineon company) or
# an affiliate of Cypress Semiconductor Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Any additional components to apply when using this board.
BSP_COMPONENTS:=

# Any additional defines to apply when using this board.
BSP_DEFINES:=

# Path to the flash loaders to patch for this board
CY_QSPI_FLM_DIR?=$(MTB_TOOLS__TARGET_DIR)/config/FlashLoaders/

# Path to the patched flash loaders for this board
CY_QSPI_FLM_DIR_OUTPUT?=$(MTB_TOOLS__TARGET_DIR)/config/GeneratedSource/

APPTYPE?=flash
VCORE_ATTRS?=NON_SECURE
CORE?=CM33
ifeq ($(CORE), CM33)
# Default nsc_veneer file - if no NSC functions are defined in the application
# the linking will fail specifying that no symbols were found. In those cases
# simply remove the NSC_VENEER specification or set to the empty string in the
# application makefile
NSC_VENEER?=../proj_cm33_s/nsc_veneer.o
endif

ifneq (,$(filter $(TOOLCHAIN),GCC_ARM LLVM_ARM))
# To pick up pse84_common.ld
LDFLAGS += -Xlinker -L $(MTB_TOOLS__TARGET_DIR)/COMPONENT_CM33/TOOLCHAIN_$(TOOLCHAIN)
LDFLAGS += -Xlinker -L $(MTB_TOOLS__TARGET_DIR)/config/GeneratedSource
else ifeq ($(TOOLCHAIN),ARM)
LDFLAGS += --undefined=__scatterload_copy
endif

# Specify the path to the linker script to use
ifneq (,$(filter $(TOOLCHAIN),GCC_ARM LLVM_ARM))
    BSP_LINKER_SCRIPT_EXT:=ld
else ifeq ($(TOOLCHAIN),ARM)
    BSP_LINKER_SCRIPT_EXT:=sct
else ifeq ($(TOOLCHAIN),IAR)
    BSP_LINKER_SCRIPT_EXT:=icf
endif


ifeq ($(VCORE_ATTRS),NON_SECURE)

ifeq ($(CORE), CM33)
MTB_BSP__LINKER_SCRIPT:=$(MTB_TOOLS__TARGET_DIR)/COMPONENT_$(CORE)/TOOLCHAIN_$(TOOLCHAIN)/pse84_ns_cm33.$(BSP_LINKER_SCRIPT_EXT)
else
MTB_BSP__LINKER_SCRIPT:=$(MTB_TOOLS__TARGET_DIR)/COMPONENT_$(CORE)/TOOLCHAIN_$(TOOLCHAIN)/pse84_ns_cm55.$(BSP_LINKER_SCRIPT_EXT)
endif

COMPONENTS+=NON_SECURE_DEVICE

else
MTB_BSP__LINKER_SCRIPT:=$(MTB_TOOLS__TARGET_DIR)/COMPONENT_$(CORE)/TOOLCHAIN_$(TOOLCHAIN)/pse84_s_cm33.$(BSP_LINKER_SCRIPT_EXT)
COMPONENTS+=SECURE_DRIVERS SECURE_DEVICE
endif

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################
