#include "mtb_stl_post_cfg.h"

const cy_stc_tcpwm_counter_config_t ifx_timer_config =
{
        .period = 1000,
        .clockPrescaler = CY_TCPWM_COUNTER_PRESCALER_DIVBY_1,
        .runMode = CY_TCPWM_COUNTER_CONTINUOUS,
        .countDirection = CY_TCPWM_COUNTER_COUNT_UP,
        .compareOrCapture = CY_TCPWM_COUNTER_MODE_CAPTURE,
        .compare0 = 16384,
        .compare1 = 16384,
        .enableCompareSwap = false,
        .interruptSources = CY_TCPWM_INT_ON_TC,
        .captureInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3U,
        .captureInput = CY_TCPWM_INPUT_0,
        .reloadInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3U,
        .reloadInput = CY_TCPWM_INPUT_0,
        .startInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3U,
        .startInput = CY_TCPWM_INPUT_0,
        .stopInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3U,
        .stopInput = CY_TCPWM_INPUT_0,
        .countInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3U,
        .countInput = CY_TCPWM_INPUT_1,
};

const cy_stc_tcpwm_counter_config_t ifx_clk_test_timer_config = {
        .period = 24000,
        .clockPrescaler = CY_TCPWM_COUNTER_PRESCALER_DIVBY_1,
        .runMode = CY_TCPWM_COUNTER_ONESHOT,
        .countDirection = CY_TCPWM_COUNTER_COUNT_UP,
        .compareOrCapture = CY_TCPWM_COUNTER_MODE_CAPTURE,
        .compare0 = 16384,
        .compare1 = 16384,
        .enableCompareSwap = false,
        .interruptSources = CY_TCPWM_INT_ON_TC,
        .captureInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3,
        .captureInput = CY_TCPWM_INPUT_0,
        .reloadInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3,
        .reloadInput = CY_TCPWM_INPUT_0,
        .startInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3,
        .startInput = CY_TCPWM_INPUT_0,
        .stopInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3,
        .stopInput = CY_TCPWM_INPUT_0,
        .countInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3,
        .countInput = CY_TCPWM_INPUT_1,
};

const cy_stc_sar_channel_config_t ifx_dut_sar_adc_ch_0_cfg =
{
    .addr = (cy_en_sar_chan_config_port_pin_addr_t)(IFX_SAR0_VPLUS0_PIN |
		    (IFX_SAR0_VPLUS0_PORT << SAR_CHAN_CONFIG_PORT_ADDR_Pos)),
    .differential = false,
    .resolution = CY_SAR_MAX_RES,
    .avgEn = false,
    .sampleTimeSel = CY_SAR_SAMPLE_TIME_0,
    .rangeIntrEn = false,
    .satIntrEn = false,
};

const cy_stc_sar_config_t ifx_dut_sar_adc_cfg =
{
    .vrefSel = CY_SAR_VREF_SEL_VDDA,
    .vrefBypCapEn = false,
    .negSel = CY_SAR_NEG_SEL_VSSA_KELVIN,
    .negVref = CY_SAR_NEGVREF_HW,
    .boostPump = false,
    .power = CY_SAR_QUARTER_PWR,
    .sarMuxDsEn = false,
    .switchDisable = false,
    .subResolution = CY_SAR_SUB_RESOLUTION_8B,
    .leftAlign = false,
    .singleEndedSigned = true,
    .differentialSigned = true,
    .avgCnt = CY_SAR_AVG_CNT_2,
    .avgShift = true,
    .trigMode = CY_SAR_TRIGGER_MODE_FW_ONLY,
    .eosEn = false,
    .sampleTime0 = 82,
    .sampleTime1 = 2,
    .sampleTime2 = 2,
    .sampleTime3 = 2,
    .rangeThresLow = 0UL,
    .rangeThresHigh = 0UL,
    .rangeCond = CY_SAR_RANGE_COND_BELOW,
    .chanEn = 1UL,
    .channelConfig = {&ifx_dut_sar_adc_ch_0_cfg, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
	    					NULL, NULL, NULL, NULL, NULL , NULL, NULL, NULL},
    .routingConfig = NULL,
    .vrefMvValue = 5000UL,
};

const cy_stc_scb_uart_config_t ifx_uart_test_cfg =
{
    .uartMode = CY_SCB_UART_STANDARD,
    .enableMutliProcessorMode = false,
    .smartCardRetryOnNack = false,
    .irdaInvertRx = false,
    .irdaEnableLowPowerReceiver = false,
    .enableLinMode = false,
    .oversample = 8,
    .enableMsbFirst = false,
    .dataWidth = 8UL,
    .parity = CY_SCB_UART_PARITY_NONE,
    .stopBits = CY_SCB_UART_STOP_BITS_1,
    .enableInputFilter = false,
    .breakWidth = 11UL,
    .breakLevel = false,
    .dropOnFrameError = false,
    .dropOnParityError = false,
    .receiverAddress = 0x0UL,
    .receiverAddressMask = 0x0UL,
    .acceptAddrInFifo = false,
    .enableCts = false,
    .ctsPolarity = CY_SCB_UART_ACTIVE_LOW,
    .rtsRxFifoLevel = 0UL,
    .rtsPolarity = CY_SCB_UART_ACTIVE_LOW,
    .rxFifoTriggerLevel = 7UL,
    .rxFifoIntEnableMask = 0UL,
    .txFifoTriggerLevel = 0UL,
    .txFifoIntEnableMask = 0UL,
};

const cy_stc_tcpwm_counter_config_t ifx_timer_counter_config = {
        .period = 32768,
        .clockPrescaler = CY_TCPWM_COUNTER_PRESCALER_DIVBY_1,
        .runMode = CY_TCPWM_COUNTER_ONESHOT,
        .countDirection = CY_TCPWM_COUNTER_COUNT_UP,
        .compareOrCapture = CY_TCPWM_COUNTER_MODE_COMPARE,
        .compare0 = 16384,
        .compare1 = 16384,
        .enableCompareSwap = false,
        .interruptSources = CY_TCPWM_INT_ON_CC,
        .captureInputMode = 0x3U,
        .captureInput = CY_TCPWM_INPUT_0,
        .reloadInputMode = 0x3U,
        .reloadInput = CY_TCPWM_INPUT_0,
        .startInputMode = 0x3U,
        .startInput = CY_TCPWM_INPUT_0,
        .stopInputMode = 0x3U,
        .stopInput = CY_TCPWM_INPUT_0,
        .countInputMode = 0x3U,
        .countInput = CY_TCPWM_INPUT_1,
};

const cy_stc_tcpwm_pwm_config_t ifx_pwm_config = {
        .pwmMode            = CY_TCPWM_PWM_MODE_PWM,
        .clockPrescaler     = CY_TCPWM_PWM_PRESCALER_DIVBY_1,
        .pwmAlignment       = CY_TCPWM_PWM_LEFT_ALIGN,
        .deadTimeClocks     = 0,
        .runMode            = CY_TCPWM_PWM_CONTINUOUS,
        .period0            = 32768,
        .period1            = 32768,
        .enablePeriodSwap   = false,
        .compare0           = 16384,
        .compare1           = 16384,
        .enableCompareSwap  = false,
        .interruptSources   = CY_TCPWM_INT_ON_TC,
        .invertPWMOut       = CY_TCPWM_PWM_INVERT_DISABLE,
        .invertPWMOutN      = CY_TCPWM_PWM_INVERT_DISABLE,
        .killMode           = CY_TCPWM_PWM_STOP_ON_KILL,
        .swapInputMode      = 0x3U,
        .swapInput          = CY_TCPWM_INPUT_0,
        .reloadInputMode    = 0x3U,
        .reloadInput        = CY_TCPWM_INPUT_0,
        .startInputMode     = 0x3U,
        .startInput         = CY_TCPWM_INPUT_0,
        .killInputMode      = 0x3U,
        .killInput          = CY_TCPWM_INPUT_0,
        .countInputMode     = 0x3U,
        .countInput         = CY_TCPWM_INPUT_1,
};

const cy_stc_tcpwm_pwm_config_t ifx_pwm_gatekill_config =
{
    .pwmMode = CY_TCPWM_PWM_MODE_PWM,
    .clockPrescaler = CY_TCPWM_PWM_PRESCALER_DIVBY_1,
    .pwmAlignment = CY_TCPWM_PWM_LEFT_ALIGN,
    .deadTimeClocks = 0,
    .runMode = CY_TCPWM_PWM_CONTINUOUS,
    .period0 = 10000,
    .period1 = 32768,
    .enablePeriodSwap = false,
    .compare0 = 10000,
    .compare1 = 16384,
    .enableCompareSwap = false,
    .interruptSources = CY_TCPWM_INT_NONE,
    .invertPWMOut = CY_TCPWM_PWM_INVERT_DISABLE,
    .invertPWMOutN = CY_TCPWM_PWM_INVERT_DISABLE,
    .killMode = CY_TCPWM_PWM_STOP_ON_KILL,
    .swapInputMode = 0x3U,
    .swapInput = CY_TCPWM_INPUT_0,
    .reloadInputMode = 0x3U,
    .reloadInput = CY_TCPWM_INPUT_0,
    .startInputMode = 0x3U,
    .startInput = CY_TCPWM_INPUT_0,
    .killInputMode = 0x3U,
    .killInput = CY_TCPWM_INPUT_0,
    .countInputMode = 0x3U,
    .countInput = CY_TCPWM_INPUT_1,
};

const cy_stc_scb_uart_config_t ifx_uart_master_config =
{
    .uartMode = CY_SCB_UART_STANDARD,
    .enableMutliProcessorMode = false,
    .smartCardRetryOnNack = false,
    .irdaInvertRx = false,
    .irdaEnableLowPowerReceiver = false,
    .enableLinMode = false,
    .oversample = 8,
    .enableMsbFirst = false,
    .dataWidth = 8UL,
    .parity = CY_SCB_UART_PARITY_NONE,
    .stopBits = CY_SCB_UART_STOP_BITS_1,
    .enableInputFilter = false,
    .breakWidth = 11UL,
    .breakLevel = false,
    .dropOnFrameError = false,
    .dropOnParityError = false,
    .receiverAddress = 0x0UL,
    .receiverAddressMask = 0x0UL,
    .acceptAddrInFifo = false,
    .enableCts = false,
    .ctsPolarity = CY_SCB_UART_ACTIVE_LOW,
    .rtsRxFifoLevel = 0UL,
    .rtsPolarity = CY_SCB_UART_ACTIVE_LOW,
    .rxFifoTriggerLevel = 7UL,
    .rxFifoIntEnableMask = 0UL,
    .txFifoTriggerLevel = 0UL,
    .txFifoIntEnableMask = 0UL,
};

const cy_stc_scb_uart_config_t ifx_uart_slave_cfg =
{
    .uartMode = CY_SCB_UART_STANDARD,
    .enableMutliProcessorMode = false,
    .smartCardRetryOnNack = false,
    .irdaInvertRx = false,
    .irdaEnableLowPowerReceiver = false,
    .enableLinMode = false,
    .oversample = 8,
    .enableMsbFirst = false,
    .dataWidth = 8UL,
    .parity = CY_SCB_UART_PARITY_NONE,
    .stopBits = CY_SCB_UART_STOP_BITS_1,
    .enableInputFilter = false,
    .breakWidth = 11UL,
    .breakLevel = false,
    .dropOnFrameError = false,
    .dropOnParityError = false,
    .receiverAddress = 0x0UL,
    .receiverAddressMask = 0x0UL,
    .acceptAddrInFifo = false,
    .enableCts = false,
    .ctsPolarity = CY_SCB_UART_ACTIVE_LOW,
    .rtsRxFifoLevel = 0UL,
    .rtsPolarity = CY_SCB_UART_ACTIVE_LOW,
    .rxFifoTriggerLevel = 7UL,
    .rxFifoIntEnableMask = 0UL,
    .txFifoTriggerLevel = 0UL,
    .txFifoIntEnableMask = 0UL,
};

const cy_stc_tcpwm_counter_config_t ifx_timer_uart_master_cfg =
{
    .period = 1000,
    .clockPrescaler = CY_TCPWM_COUNTER_PRESCALER_DIVBY_1,
    .runMode = CY_TCPWM_COUNTER_CONTINUOUS,
    .countDirection = CY_TCPWM_COUNTER_COUNT_DOWN,
    .compareOrCapture = CY_TCPWM_COUNTER_MODE_CAPTURE,
    .compare0 = 16384,
    .compare1 = 16384,
    .enableCompareSwap = false,
    .interruptSources = CY_TCPWM_INT_ON_TC,
    .captureInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3U,
    .captureInput = CY_TCPWM_INPUT_0,
    .reloadInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3U,
    .reloadInput = CY_TCPWM_INPUT_0,
    .startInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3U,
    .startInput = CY_TCPWM_INPUT_0,
    .stopInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3U,
    .stopInput = CY_TCPWM_INPUT_0,
    .countInputMode = IFX_TCPWM_INPUT_DISABLED & 0x3U,
    .countInput = CY_TCPWM_INPUT_1,
};
