/***************************************************************************//**
* \file cyip_sflash_256_2.h
*
* \brief
* SFLASH IP definitions
*
********************************************************************************
* \copyright
* (c) (2016-2025), Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
*
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#ifndef _CYIP_SFLASH_256_2_H_
#define _CYIP_SFLASH_256_2_H_

#include "cyip_headers.h"

/*******************************************************************************
*                                    SFLASH
*******************************************************************************/

#define SFLASH_SECTION_SIZE                     0x00000800UL

/**
  * \brief Supervisory Flash Area (Cypress Trim & Wounding Info) (SFLASH)
  */
typedef struct {
   __IM uint8_t  RESERVED[267];
  __IOM uint8_t  MSCLP_TRIM_CTL_46;             /*!< 0x0000010B CSD0 Trim Control for 46MHz */
  __IOM uint8_t  MSCLP_CLK_IMO_TRIM1_46;        /*!< 0x0000010C Local IMO Trim Register 1 for 46MHz */
  __IOM uint8_t  MSCLP_CLK_IMO_TRIM2_46;        /*!< 0x0000010D Local IMO Trim Register 2 for 46MHz */
  __IOM uint8_t  MSCLP_CLK_IMO_TRIM3_46;        /*!< 0x0000010E Local IMO Trim Register 3 for 46MHz */
   __IM uint8_t  RESERVED1[5];
  __IOM uint8_t  MSCLP_TRIM_CTL_38;             /*!< 0x00000114 CSD0 Trim Control for 38MHz */
  __IOM uint8_t  MSCLP_CLK_IMO_TRIM1_38;        /*!< 0x00000115 Local IMO Trim Register 1 for 38MHz */
  __IOM uint8_t  MSCLP_CLK_IMO_TRIM2_38;        /*!< 0x00000116 Local IMO Trim Register 2 for 38MHz */
  __IOM uint8_t  MSCLP_CLK_IMO_TRIM3_38;        /*!< 0x00000117 Local IMO Trim Register 3 for 38MHz */
   __IM uint8_t  RESERVED2[5];
  __IOM uint8_t  MSCLP_TRIM_CTL_25;             /*!< 0x0000011D CSD0 Trim Control for 25MHz */
  __IOM uint8_t  MSCLP_CLK_IMO_TRIM1_25;        /*!< 0x0000011E Local IMO Trim Register 1 for 25MHz */
  __IOM uint8_t  MSCLP_CLK_IMO_TRIM2_25;        /*!< 0x0000011F Local IMO Trim Register 2 for 25MHz */
  __IOM uint8_t  MSCLP_CLK_IMO_TRIM3_25;        /*!< 0x00000120 Local IMO Trim Register 3 for 25MHz */
   __IM uint8_t  RESERVED3[25];
  __IOM uint8_t  CREF_COEFF0;                   /*!< 0x0000013A CREF_COEFF0 */
  __IOM uint8_t  CREF_COEFF1;                   /*!< 0x0000013B CREF_COEFF1 */
  __IOM uint8_t  CFINE_COEFF0;                  /*!< 0x0000013C CFINE_COEFF0 */
  __IOM uint8_t  CFINE_COEFF1;                  /*!< 0x0000013D CFINE_COEFF1 */
   __IM uint16_t RESERVED4[131];
  __IOM uint32_t SILICON_ID;                    /*!< 0x00000244 Silicon ID */
   __IM uint32_t RESERVED5[2];
  __IOM uint16_t HIB_KEY_DELAY;                 /*!< 0x00000250 Hibernate wakeup value for PWR_KEY_DELAY */
  __IOM uint16_t DPSLP_KEY_DELAY;               /*!< 0x00000252 DeepSleep wakeup value for PWR_KEY_DELAY */
   __IM uint32_t RESERVED6;
  __IOM uint32_t SWD_LISTEN;                    /*!< 0x00000258 Listen Window Length */
  __IOM uint32_t FLASH_START;                   /*!< 0x0000025C Flash Image Start Address */
  __IOM uint8_t  CSDV2_CSD0_ADC_TRIM1;          /*!< 0x00000260 Low byte of CSDv2 Calibration */
  __IOM uint8_t  CSDV2_CSD0_ADC_TRIM2;          /*!< 0x00000261 CSDV2 CSD0 ADC TRIM2 */
   __IM uint16_t RESERVED7;
  __IOM uint16_t SAR_TEMP_MULTIPLIER;           /*!< 0x00000264 SAR Temperature Sensor Multiplication Factor */
  __IOM uint16_t SAR_TEMP_OFFSET;               /*!< 0x00000266 SAR Temperature Sensor Offset */
   __IM uint32_t RESERVED8[6];
  __IOM uint8_t  CSDV2_CSD1_ADC_TRIM1;          /*!< 0x00000280 CSDV2 CSD1 ADC TRIM 1 */
  __IOM uint8_t  CSDV2_CSD1_ADC_TRIM2;          /*!< 0x00000281 CSDV2 CSD1 ADC TRIM2 */
   __IM uint16_t RESERVED9[94];
  __IOM uint8_t  IMO_TRIM_USBMODE_24;           /*!< 0x0000033E USB IMO TRIM 24MHz */
  __IOM uint8_t  IMO_TRIM_USBMODE_48;           /*!< 0x0000033F USB IMO TRIM 48MHz */
   __IM uint32_t RESERVED10[3];
  __IOM uint8_t  IMO_TCTRIM_LT[25];             /*!< 0x0000034C IMO TempCo Trim Register (SRSS-Lite) */
  __IOM uint8_t  IMO_TRIM_LT[25];               /*!< 0x00000365 IMO Frequency Trim Register (SRSS-Lite) */
   __IM uint16_t RESERVED11;
  __IOM uint8_t  DYN_IMO_ADC_DIODE_100C_LSB;    /*!< 0x00000380 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_ADC_DIODE_100C_MSB;    /*!< 0x00000381 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_ADC_DIODE_N40C_LSB;    /*!< 0x00000382 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_ADC_DIODE_N40C_MSB;    /*!< 0x00000383 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_ADC_DIODE_25C_LSB;     /*!< 0x00000384 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_ADC_DIODE_25C_MSB;     /*!< 0x00000385 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_ADC_DIODE_RMHT_LSB;    /*!< 0x00000386 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_ADC_DIODE_RMHT_MSB;    /*!< 0x00000387 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_ADC_DIODE_RMC_LSB;     /*!< 0x00000388 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_ADC_DIODE_RMC_MSB;     /*!< 0x00000389 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_24MHZ_TRIM_100C;       /*!< 0x0000038A Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_28MHZ_TRIM_100C;       /*!< 0x0000038B Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_32MHZ_TRIM_100C;       /*!< 0x0000038C Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_36MHZ_TRIM_100C;       /*!< 0x0000038D Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_40MHZ_TRIM_100C;       /*!< 0x0000038E Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_44MHZ_TRIM_100C;       /*!< 0x0000038F Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_48MHZ_TRIM_100C;       /*!< 0x00000390 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_24MHZ_TRIM_N40C;       /*!< 0x00000391 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_28MHZ_TRIM_N40C;       /*!< 0x00000392 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_32MHZ_TRIM_N40C;       /*!< 0x00000393 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_36MHZ_TRIM_N40C;       /*!< 0x00000394 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_40MHZ_TRIM_N40C;       /*!< 0x00000395 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_44MHZ_TRIM_N40C;       /*!< 0x00000396 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_48MHZ_TRIM_N40C;       /*!< 0x00000397 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_24MHZ_TRIM_25C;        /*!< 0x00000398 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_28MHZ_TRIM_25C;        /*!< 0x00000399 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_32MHZ_TRIM_25C;        /*!< 0x0000039A Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_36MHZ_TRIM_25C;        /*!< 0x0000039B Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_40MHZ_TRIM_25C;        /*!< 0x0000039C Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_44MHZ_TRIM_25C;        /*!< 0x0000039D Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_48MHZ_TRIM_25C;        /*!< 0x0000039E Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_24MHZ_TRIM_RMHT;       /*!< 0x0000039F Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_28MHZ_TRIM_RMHT;       /*!< 0x000003A0 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_32MHZ_TRIM_RMHT;       /*!< 0x000003A1 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_36MHZ_TRIM_RMHT;       /*!< 0x000003A2 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_40MHZ_TRIM_RMHT;       /*!< 0x000003A3 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_44MHZ_TRIM_RMHT;       /*!< 0x000003A4 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_48MHZ_TRIM_RMHT;       /*!< 0x000003A5 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_24MHZ_TRIM_RMC;        /*!< 0x000003A6 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_28MHZ_TRIM_RMC;        /*!< 0x000003A7 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_32MHZ_TRIM_RMC;        /*!< 0x000003A8 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_36MHZ_TRIM_RMC;        /*!< 0x000003A9 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_40MHZ_TRIM_RMC;        /*!< 0x000003AA Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_44MHZ_TRIM_RMC;        /*!< 0x000003AB Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_48MHZ_TRIM_RMC;        /*!< 0x000003AC Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_OFFSET_24MHZ_HOT;      /*!< 0x000003AD Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_OFFSET_28MHZ_HOT;      /*!< 0x000003AE Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_OFFSET_32MHZ_HOT;      /*!< 0x000003AF Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_OFFSET_36MHZ_HOT;      /*!< 0x000003B0 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_OFFSET_40MHZ_HOT;      /*!< 0x000003B1 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_OFFSET_44MHZ_HOT;      /*!< 0x000003B2 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_OFFSET_48MHZ_HOT;      /*!< 0x000003B3 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_OFFSET_24MHZ_COLD;     /*!< 0x000003B4 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_OFFSET_28MHZ_COLD;     /*!< 0x000003B5 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_OFFSET_32MHZ_COLD;     /*!< 0x000003B6 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_OFFSET_36MHZ_COLD;     /*!< 0x000003B7 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_OFFSET_40MHZ_COLD;     /*!< 0x000003B8 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_OFFSET_44MHZ_COLD;     /*!< 0x000003B9 Dynamic IMO Trim */
  __IOM uint8_t  DYN_IMO_OFFSET_48MHZ_COLD;     /*!< 0x000003BA Dynamic IMO Trim */
} SFLASH_Type;                                  /*!< Size = 955 (0x3BB) */


/* SFLASH.MSCLP_TRIM_CTL_46 */
#define SFLASH_MSCLP_TRIM_CTL_46_MSC_TRIM_CTL1_Pos 0UL
#define SFLASH_MSCLP_TRIM_CTL_46_MSC_TRIM_CTL1_Msk 0xFFUL
/* SFLASH.MSCLP_CLK_IMO_TRIM1_46 */
#define SFLASH_MSCLP_CLK_IMO_TRIM1_46_TRIM1_Pos 0UL
#define SFLASH_MSCLP_CLK_IMO_TRIM1_46_TRIM1_Msk 0xFFUL
/* SFLASH.MSCLP_CLK_IMO_TRIM2_46 */
#define SFLASH_MSCLP_CLK_IMO_TRIM2_46_TRIM2_Pos 0UL
#define SFLASH_MSCLP_CLK_IMO_TRIM2_46_TRIM2_Msk 0xFFUL
/* SFLASH.MSCLP_CLK_IMO_TRIM3_46 */
#define SFLASH_MSCLP_CLK_IMO_TRIM3_46_TRIM3_Pos 0UL
#define SFLASH_MSCLP_CLK_IMO_TRIM3_46_TRIM3_Msk 0xFFUL
/* SFLASH.MSCLP_TRIM_CTL_38 */
#define SFLASH_MSCLP_TRIM_CTL_38_MSC_TRIM_CTL2_Pos 0UL
#define SFLASH_MSCLP_TRIM_CTL_38_MSC_TRIM_CTL2_Msk 0xFFUL
/* SFLASH.MSCLP_CLK_IMO_TRIM1_38 */
#define SFLASH_MSCLP_CLK_IMO_TRIM1_38_TRIM1_Pos 0UL
#define SFLASH_MSCLP_CLK_IMO_TRIM1_38_TRIM1_Msk 0xFFUL
/* SFLASH.MSCLP_CLK_IMO_TRIM2_38 */
#define SFLASH_MSCLP_CLK_IMO_TRIM2_38_TRIM2_Pos 0UL
#define SFLASH_MSCLP_CLK_IMO_TRIM2_38_TRIM2_Msk 0xFFUL
/* SFLASH.MSCLP_CLK_IMO_TRIM3_38 */
#define SFLASH_MSCLP_CLK_IMO_TRIM3_38_TRIM3_Pos 0UL
#define SFLASH_MSCLP_CLK_IMO_TRIM3_38_TRIM3_Msk 0xFFUL
/* SFLASH.MSCLP_TRIM_CTL_25 */
#define SFLASH_MSCLP_TRIM_CTL_25_MSC_TRIM_CTL3_Pos 0UL
#define SFLASH_MSCLP_TRIM_CTL_25_MSC_TRIM_CTL3_Msk 0xFFUL
/* SFLASH.MSCLP_CLK_IMO_TRIM1_25 */
#define SFLASH_MSCLP_CLK_IMO_TRIM1_25_TRIM1_Pos 0UL
#define SFLASH_MSCLP_CLK_IMO_TRIM1_25_TRIM1_Msk 0xFFUL
/* SFLASH.MSCLP_CLK_IMO_TRIM2_25 */
#define SFLASH_MSCLP_CLK_IMO_TRIM2_25_TRIM2_Pos 0UL
#define SFLASH_MSCLP_CLK_IMO_TRIM2_25_TRIM2_Msk 0xFFUL
/* SFLASH.MSCLP_CLK_IMO_TRIM3_25 */
#define SFLASH_MSCLP_CLK_IMO_TRIM3_25_TRIM3_Pos 0UL
#define SFLASH_MSCLP_CLK_IMO_TRIM3_25_TRIM3_Msk 0xFFUL
/* SFLASH.CREF_COEFF0 */
#define SFLASH_CREF_COEFF0_MSC_CREF_COEFF0_Pos  0UL
#define SFLASH_CREF_COEFF0_MSC_CREF_COEFF0_Msk  0xFFUL
/* SFLASH.CREF_COEFF1 */
#define SFLASH_CREF_COEFF1_MSC_CREF_COEFF1_Pos  0UL
#define SFLASH_CREF_COEFF1_MSC_CREF_COEFF1_Msk  0xFFUL
/* SFLASH.CFINE_COEFF0 */
#define SFLASH_CFINE_COEFF0_MSC_CFINE_COEFF0_Pos 0UL
#define SFLASH_CFINE_COEFF0_MSC_CFINE_COEFF0_Msk 0xFFUL
/* SFLASH.CFINE_COEFF1 */
#define SFLASH_CFINE_COEFF1_MSC_CFINE_COEFF1_Pos 0UL
#define SFLASH_CFINE_COEFF1_MSC_CFINE_COEFF1_Msk 0xFFUL
/* SFLASH.SILICON_ID */
#define SFLASH_SILICON_ID_ID_Pos                0UL
#define SFLASH_SILICON_ID_ID_Msk                0xFFFFUL
/* SFLASH.HIB_KEY_DELAY */
#define SFLASH_HIB_KEY_DELAY_WAKEUP_HOLDOFF_Pos 0UL
#define SFLASH_HIB_KEY_DELAY_WAKEUP_HOLDOFF_Msk 0x3FFUL
/* SFLASH.DPSLP_KEY_DELAY */
#define SFLASH_DPSLP_KEY_DELAY_WAKEUP_HOLDOFF_Pos 0UL
#define SFLASH_DPSLP_KEY_DELAY_WAKEUP_HOLDOFF_Msk 0x3FFUL
/* SFLASH.SWD_LISTEN */
#define SFLASH_SWD_LISTEN_CYCLES_Pos            0UL
#define SFLASH_SWD_LISTEN_CYCLES_Msk            0xFFFFFFFFUL
/* SFLASH.FLASH_START */
#define SFLASH_FLASH_START_ADDRESS_Pos          0UL
#define SFLASH_FLASH_START_ADDRESS_Msk          0xFFFFFFFFUL
/* SFLASH.CSDV2_CSD0_ADC_TRIM1 */
#define SFLASH_CSDV2_CSD0_ADC_TRIM1_CSD_ADC_CAL_LSB_Pos 0UL
#define SFLASH_CSDV2_CSD0_ADC_TRIM1_CSD_ADC_CAL_LSB_Msk 0xFFUL
/* SFLASH.CSDV2_CSD0_ADC_TRIM2 */
#define SFLASH_CSDV2_CSD0_ADC_TRIM2_CSD_ADC_CAL_MSB_Pos 0UL
#define SFLASH_CSDV2_CSD0_ADC_TRIM2_CSD_ADC_CAL_MSB_Msk 0xFFUL
/* SFLASH.SAR_TEMP_MULTIPLIER */
#define SFLASH_SAR_TEMP_MULTIPLIER_TEMP_MULTIPLIER_Pos 0UL
#define SFLASH_SAR_TEMP_MULTIPLIER_TEMP_MULTIPLIER_Msk 0xFFFFUL
/* SFLASH.SAR_TEMP_OFFSET */
#define SFLASH_SAR_TEMP_OFFSET_TEMP_OFFSET_Pos  0UL
#define SFLASH_SAR_TEMP_OFFSET_TEMP_OFFSET_Msk  0xFFFFUL
/* SFLASH.CSDV2_CSD1_ADC_TRIM1 */
#define SFLASH_CSDV2_CSD1_ADC_TRIM1_ADCTRIM_1P2V_Pos 0UL
#define SFLASH_CSDV2_CSD1_ADC_TRIM1_ADCTRIM_1P2V_Msk 0x1FUL
#define SFLASH_CSDV2_CSD1_ADC_TRIM1_ADCTRIM_2P4V_2_0_Pos 5UL
#define SFLASH_CSDV2_CSD1_ADC_TRIM1_ADCTRIM_2P4V_2_0_Msk 0xE0UL
/* SFLASH.CSDV2_CSD1_ADC_TRIM2 */
#define SFLASH_CSDV2_CSD1_ADC_TRIM2_ADCTRIM_3P84V_2_0_Pos 0UL
#define SFLASH_CSDV2_CSD1_ADC_TRIM2_ADCTRIM_3P84V_2_0_Msk 0x1FUL
#define SFLASH_CSDV2_CSD1_ADC_TRIM2_ADCTRIM_2P4V_5_4_Pos 5UL
#define SFLASH_CSDV2_CSD1_ADC_TRIM2_ADCTRIM_2P4V_5_4_Msk 0x60UL
/* SFLASH.IMO_TRIM_USBMODE_24 */
#define SFLASH_IMO_TRIM_USBMODE_24_TRIM_24_Pos  0UL
#define SFLASH_IMO_TRIM_USBMODE_24_TRIM_24_Msk  0xFFUL
/* SFLASH.IMO_TRIM_USBMODE_48 */
#define SFLASH_IMO_TRIM_USBMODE_48_TRIM_24_Pos  0UL
#define SFLASH_IMO_TRIM_USBMODE_48_TRIM_24_Msk  0xFFUL
/* SFLASH.IMO_TCTRIM_LT */
#define SFLASH_IMO_TCTRIM_LT_STEPSIZE_Pos       0UL
#define SFLASH_IMO_TCTRIM_LT_STEPSIZE_Msk       0x1FUL
#define SFLASH_IMO_TCTRIM_LT_TCTRIM_Pos         5UL
#define SFLASH_IMO_TCTRIM_LT_TCTRIM_Msk         0x60UL
/* SFLASH.IMO_TRIM_LT */
#define SFLASH_IMO_TRIM_LT_OFFSET_Pos           0UL
#define SFLASH_IMO_TRIM_LT_OFFSET_Msk           0xFFUL
/* SFLASH.DYN_IMO_ADC_DIODE_100C_LSB */
#define SFLASH_DYN_IMO_ADC_DIODE_100C_LSB_ADC_DIODE_1_Pos 0UL
#define SFLASH_DYN_IMO_ADC_DIODE_100C_LSB_ADC_DIODE_1_Msk 0xFFUL
/* SFLASH.DYN_IMO_ADC_DIODE_100C_MSB */
#define SFLASH_DYN_IMO_ADC_DIODE_100C_MSB_ADC_DIODE_2_Pos 0UL
#define SFLASH_DYN_IMO_ADC_DIODE_100C_MSB_ADC_DIODE_2_Msk 0xFFUL
/* SFLASH.DYN_IMO_ADC_DIODE_N40C_LSB */
#define SFLASH_DYN_IMO_ADC_DIODE_N40C_LSB_ADC_DIODE_3_Pos 0UL
#define SFLASH_DYN_IMO_ADC_DIODE_N40C_LSB_ADC_DIODE_3_Msk 0xFFUL
/* SFLASH.DYN_IMO_ADC_DIODE_N40C_MSB */
#define SFLASH_DYN_IMO_ADC_DIODE_N40C_MSB_ADC_DIODE_4_Pos 0UL
#define SFLASH_DYN_IMO_ADC_DIODE_N40C_MSB_ADC_DIODE_4_Msk 0xFFUL
/* SFLASH.DYN_IMO_ADC_DIODE_25C_LSB */
#define SFLASH_DYN_IMO_ADC_DIODE_25C_LSB_ADC_DIODE_5_Pos 0UL
#define SFLASH_DYN_IMO_ADC_DIODE_25C_LSB_ADC_DIODE_5_Msk 0xFFUL
/* SFLASH.DYN_IMO_ADC_DIODE_25C_MSB */
#define SFLASH_DYN_IMO_ADC_DIODE_25C_MSB_ADC_DIODE_6_Pos 0UL
#define SFLASH_DYN_IMO_ADC_DIODE_25C_MSB_ADC_DIODE_6_Msk 0xFFUL
/* SFLASH.DYN_IMO_ADC_DIODE_RMHT_LSB */
#define SFLASH_DYN_IMO_ADC_DIODE_RMHT_LSB_ADC_DIODE_7_Pos 0UL
#define SFLASH_DYN_IMO_ADC_DIODE_RMHT_LSB_ADC_DIODE_7_Msk 0xFFUL
/* SFLASH.DYN_IMO_ADC_DIODE_RMHT_MSB */
#define SFLASH_DYN_IMO_ADC_DIODE_RMHT_MSB_ADC_DIODE_8_Pos 0UL
#define SFLASH_DYN_IMO_ADC_DIODE_RMHT_MSB_ADC_DIODE_8_Msk 0xFFUL
/* SFLASH.DYN_IMO_ADC_DIODE_RMC_LSB */
#define SFLASH_DYN_IMO_ADC_DIODE_RMC_LSB_ADC_DIODE_9_Pos 0UL
#define SFLASH_DYN_IMO_ADC_DIODE_RMC_LSB_ADC_DIODE_9_Msk 0xFFUL
/* SFLASH.DYN_IMO_ADC_DIODE_RMC_MSB */
#define SFLASH_DYN_IMO_ADC_DIODE_RMC_MSB_ADC_DIODE_10_Pos 0UL
#define SFLASH_DYN_IMO_ADC_DIODE_RMC_MSB_ADC_DIODE_10_Msk 0xFFUL
/* SFLASH.DYN_IMO_24MHZ_TRIM_100C */
#define SFLASH_DYN_IMO_24MHZ_TRIM_100C_IMO_TRIM_1_Pos 0UL
#define SFLASH_DYN_IMO_24MHZ_TRIM_100C_IMO_TRIM_1_Msk 0xFFUL
/* SFLASH.DYN_IMO_28MHZ_TRIM_100C */
#define SFLASH_DYN_IMO_28MHZ_TRIM_100C_IMO_TRIM_2_Pos 0UL
#define SFLASH_DYN_IMO_28MHZ_TRIM_100C_IMO_TRIM_2_Msk 0xFFUL
/* SFLASH.DYN_IMO_32MHZ_TRIM_100C */
#define SFLASH_DYN_IMO_32MHZ_TRIM_100C_IMO_TRIM_3_Pos 0UL
#define SFLASH_DYN_IMO_32MHZ_TRIM_100C_IMO_TRIM_3_Msk 0xFFUL
/* SFLASH.DYN_IMO_36MHZ_TRIM_100C */
#define SFLASH_DYN_IMO_36MHZ_TRIM_100C_IMO_TRIM_4_Pos 0UL
#define SFLASH_DYN_IMO_36MHZ_TRIM_100C_IMO_TRIM_4_Msk 0xFFUL
/* SFLASH.DYN_IMO_40MHZ_TRIM_100C */
#define SFLASH_DYN_IMO_40MHZ_TRIM_100C_IMO_TRIM_5_Pos 0UL
#define SFLASH_DYN_IMO_40MHZ_TRIM_100C_IMO_TRIM_5_Msk 0xFFUL
/* SFLASH.DYN_IMO_44MHZ_TRIM_100C */
#define SFLASH_DYN_IMO_44MHZ_TRIM_100C_IMO_TRIM_6_Pos 0UL
#define SFLASH_DYN_IMO_44MHZ_TRIM_100C_IMO_TRIM_6_Msk 0xFFUL
/* SFLASH.DYN_IMO_48MHZ_TRIM_100C */
#define SFLASH_DYN_IMO_48MHZ_TRIM_100C_IMO_TRIM_7_Pos 0UL
#define SFLASH_DYN_IMO_48MHZ_TRIM_100C_IMO_TRIM_7_Msk 0xFFUL
/* SFLASH.DYN_IMO_24MHZ_TRIM_N40C */
#define SFLASH_DYN_IMO_24MHZ_TRIM_N40C_IMO_TRIM_8_Pos 0UL
#define SFLASH_DYN_IMO_24MHZ_TRIM_N40C_IMO_TRIM_8_Msk 0xFFUL
/* SFLASH.DYN_IMO_28MHZ_TRIM_N40C */
#define SFLASH_DYN_IMO_28MHZ_TRIM_N40C_IMO_TRIM_9_Pos 0UL
#define SFLASH_DYN_IMO_28MHZ_TRIM_N40C_IMO_TRIM_9_Msk 0xFFUL
/* SFLASH.DYN_IMO_32MHZ_TRIM_N40C */
#define SFLASH_DYN_IMO_32MHZ_TRIM_N40C_IMO_TRIM_10_Pos 0UL
#define SFLASH_DYN_IMO_32MHZ_TRIM_N40C_IMO_TRIM_10_Msk 0xFFUL
/* SFLASH.DYN_IMO_36MHZ_TRIM_N40C */
#define SFLASH_DYN_IMO_36MHZ_TRIM_N40C_IMO_TRIM_11_Pos 0UL
#define SFLASH_DYN_IMO_36MHZ_TRIM_N40C_IMO_TRIM_11_Msk 0xFFUL
/* SFLASH.DYN_IMO_40MHZ_TRIM_N40C */
#define SFLASH_DYN_IMO_40MHZ_TRIM_N40C_IMO_TRIM_12_Pos 0UL
#define SFLASH_DYN_IMO_40MHZ_TRIM_N40C_IMO_TRIM_12_Msk 0xFFUL
/* SFLASH.DYN_IMO_44MHZ_TRIM_N40C */
#define SFLASH_DYN_IMO_44MHZ_TRIM_N40C_IMO_TRIM_13_Pos 0UL
#define SFLASH_DYN_IMO_44MHZ_TRIM_N40C_IMO_TRIM_13_Msk 0xFFUL
/* SFLASH.DYN_IMO_48MHZ_TRIM_N40C */
#define SFLASH_DYN_IMO_48MHZ_TRIM_N40C_IMO_TRIM_14_Pos 0UL
#define SFLASH_DYN_IMO_48MHZ_TRIM_N40C_IMO_TRIM_14_Msk 0xFFUL
/* SFLASH.DYN_IMO_24MHZ_TRIM_25C */
#define SFLASH_DYN_IMO_24MHZ_TRIM_25C_IMO_TRIM_15_Pos 0UL
#define SFLASH_DYN_IMO_24MHZ_TRIM_25C_IMO_TRIM_15_Msk 0xFFUL
/* SFLASH.DYN_IMO_28MHZ_TRIM_25C */
#define SFLASH_DYN_IMO_28MHZ_TRIM_25C_IMO_TRIM_16_Pos 0UL
#define SFLASH_DYN_IMO_28MHZ_TRIM_25C_IMO_TRIM_16_Msk 0xFFUL
/* SFLASH.DYN_IMO_32MHZ_TRIM_25C */
#define SFLASH_DYN_IMO_32MHZ_TRIM_25C_IMO_TRIM_17_Pos 0UL
#define SFLASH_DYN_IMO_32MHZ_TRIM_25C_IMO_TRIM_17_Msk 0xFFUL
/* SFLASH.DYN_IMO_36MHZ_TRIM_25C */
#define SFLASH_DYN_IMO_36MHZ_TRIM_25C_IMO_TRIM_18_Pos 0UL
#define SFLASH_DYN_IMO_36MHZ_TRIM_25C_IMO_TRIM_18_Msk 0xFFUL
/* SFLASH.DYN_IMO_40MHZ_TRIM_25C */
#define SFLASH_DYN_IMO_40MHZ_TRIM_25C_IMO_TRIM_19_Pos 0UL
#define SFLASH_DYN_IMO_40MHZ_TRIM_25C_IMO_TRIM_19_Msk 0xFFUL
/* SFLASH.DYN_IMO_44MHZ_TRIM_25C */
#define SFLASH_DYN_IMO_44MHZ_TRIM_25C_IMO_TRIM_20_Pos 0UL
#define SFLASH_DYN_IMO_44MHZ_TRIM_25C_IMO_TRIM_20_Msk 0xFFUL
/* SFLASH.DYN_IMO_48MHZ_TRIM_25C */
#define SFLASH_DYN_IMO_48MHZ_TRIM_25C_IMO_TRIM_21_Pos 0UL
#define SFLASH_DYN_IMO_48MHZ_TRIM_25C_IMO_TRIM_21_Msk 0xFFUL
/* SFLASH.DYN_IMO_24MHZ_TRIM_RMHT */
#define SFLASH_DYN_IMO_24MHZ_TRIM_RMHT_IMO_TRIM_22_Pos 0UL
#define SFLASH_DYN_IMO_24MHZ_TRIM_RMHT_IMO_TRIM_22_Msk 0xFFUL
/* SFLASH.DYN_IMO_28MHZ_TRIM_RMHT */
#define SFLASH_DYN_IMO_28MHZ_TRIM_RMHT_IMO_TRIM_23_Pos 0UL
#define SFLASH_DYN_IMO_28MHZ_TRIM_RMHT_IMO_TRIM_23_Msk 0xFFUL
/* SFLASH.DYN_IMO_32MHZ_TRIM_RMHT */
#define SFLASH_DYN_IMO_32MHZ_TRIM_RMHT_IMO_TRIM_24_Pos 0UL
#define SFLASH_DYN_IMO_32MHZ_TRIM_RMHT_IMO_TRIM_24_Msk 0xFFUL
/* SFLASH.DYN_IMO_36MHZ_TRIM_RMHT */
#define SFLASH_DYN_IMO_36MHZ_TRIM_RMHT_IMO_TRIM_25_Pos 0UL
#define SFLASH_DYN_IMO_36MHZ_TRIM_RMHT_IMO_TRIM_25_Msk 0xFFUL
/* SFLASH.DYN_IMO_40MHZ_TRIM_RMHT */
#define SFLASH_DYN_IMO_40MHZ_TRIM_RMHT_IMO_TRIM_26_Pos 0UL
#define SFLASH_DYN_IMO_40MHZ_TRIM_RMHT_IMO_TRIM_26_Msk 0xFFUL
/* SFLASH.DYN_IMO_44MHZ_TRIM_RMHT */
#define SFLASH_DYN_IMO_44MHZ_TRIM_RMHT_IMO_TRIM_27_Pos 0UL
#define SFLASH_DYN_IMO_44MHZ_TRIM_RMHT_IMO_TRIM_27_Msk 0xFFUL
/* SFLASH.DYN_IMO_48MHZ_TRIM_RMHT */
#define SFLASH_DYN_IMO_48MHZ_TRIM_RMHT_IMO_TRIM_28_Pos 0UL
#define SFLASH_DYN_IMO_48MHZ_TRIM_RMHT_IMO_TRIM_28_Msk 0xFFUL
/* SFLASH.DYN_IMO_24MHZ_TRIM_RMC */
#define SFLASH_DYN_IMO_24MHZ_TRIM_RMC_IMO_TRIM_29_Pos 0UL
#define SFLASH_DYN_IMO_24MHZ_TRIM_RMC_IMO_TRIM_29_Msk 0xFFUL
/* SFLASH.DYN_IMO_28MHZ_TRIM_RMC */
#define SFLASH_DYN_IMO_28MHZ_TRIM_RMC_IMO_TRIM_30_Pos 0UL
#define SFLASH_DYN_IMO_28MHZ_TRIM_RMC_IMO_TRIM_30_Msk 0xFFUL
/* SFLASH.DYN_IMO_32MHZ_TRIM_RMC */
#define SFLASH_DYN_IMO_32MHZ_TRIM_RMC_IMO_TRIM_31_Pos 0UL
#define SFLASH_DYN_IMO_32MHZ_TRIM_RMC_IMO_TRIM_31_Msk 0xFFUL
/* SFLASH.DYN_IMO_36MHZ_TRIM_RMC */
#define SFLASH_DYN_IMO_36MHZ_TRIM_RMC_IMO_TRIM_32_Pos 0UL
#define SFLASH_DYN_IMO_36MHZ_TRIM_RMC_IMO_TRIM_32_Msk 0xFFUL
/* SFLASH.DYN_IMO_40MHZ_TRIM_RMC */
#define SFLASH_DYN_IMO_40MHZ_TRIM_RMC_IMO_TRIM_33_Pos 0UL
#define SFLASH_DYN_IMO_40MHZ_TRIM_RMC_IMO_TRIM_33_Msk 0xFFUL
/* SFLASH.DYN_IMO_44MHZ_TRIM_RMC */
#define SFLASH_DYN_IMO_44MHZ_TRIM_RMC_IMO_TRIM_34_Pos 0UL
#define SFLASH_DYN_IMO_44MHZ_TRIM_RMC_IMO_TRIM_34_Msk 0xFFUL
/* SFLASH.DYN_IMO_48MHZ_TRIM_RMC */
#define SFLASH_DYN_IMO_48MHZ_TRIM_RMC_IMO_TRIM_35_Pos 0UL
#define SFLASH_DYN_IMO_48MHZ_TRIM_RMC_IMO_TRIM_35_Msk 0xFFUL
/* SFLASH.DYN_IMO_OFFSET_24MHZ_HOT */
#define SFLASH_DYN_IMO_OFFSET_24MHZ_HOT_IMO_OFFSET_1_Pos 0UL
#define SFLASH_DYN_IMO_OFFSET_24MHZ_HOT_IMO_OFFSET_1_Msk 0xFFUL
/* SFLASH.DYN_IMO_OFFSET_28MHZ_HOT */
#define SFLASH_DYN_IMO_OFFSET_28MHZ_HOT_IMO_OFFSET_2_Pos 0UL
#define SFLASH_DYN_IMO_OFFSET_28MHZ_HOT_IMO_OFFSET_2_Msk 0xFFUL
/* SFLASH.DYN_IMO_OFFSET_32MHZ_HOT */
#define SFLASH_DYN_IMO_OFFSET_32MHZ_HOT_IMO_OFFSET_3_Pos 0UL
#define SFLASH_DYN_IMO_OFFSET_32MHZ_HOT_IMO_OFFSET_3_Msk 0xFFUL
/* SFLASH.DYN_IMO_OFFSET_36MHZ_HOT */
#define SFLASH_DYN_IMO_OFFSET_36MHZ_HOT_IMO_OFFSET_4_Pos 0UL
#define SFLASH_DYN_IMO_OFFSET_36MHZ_HOT_IMO_OFFSET_4_Msk 0xFFUL
/* SFLASH.DYN_IMO_OFFSET_40MHZ_HOT */
#define SFLASH_DYN_IMO_OFFSET_40MHZ_HOT_IMO_OFFSET_5_Pos 0UL
#define SFLASH_DYN_IMO_OFFSET_40MHZ_HOT_IMO_OFFSET_5_Msk 0xFFUL
/* SFLASH.DYN_IMO_OFFSET_44MHZ_HOT */
#define SFLASH_DYN_IMO_OFFSET_44MHZ_HOT_IMO_OFFSET_6_Pos 0UL
#define SFLASH_DYN_IMO_OFFSET_44MHZ_HOT_IMO_OFFSET_6_Msk 0xFFUL
/* SFLASH.DYN_IMO_OFFSET_48MHZ_HOT */
#define SFLASH_DYN_IMO_OFFSET_48MHZ_HOT_IMO_OFFSET_7_Pos 0UL
#define SFLASH_DYN_IMO_OFFSET_48MHZ_HOT_IMO_OFFSET_7_Msk 0xFFUL
/* SFLASH.DYN_IMO_OFFSET_24MHZ_COLD */
#define SFLASH_DYN_IMO_OFFSET_24MHZ_COLD_IMO_OFFSET_8_Pos 0UL
#define SFLASH_DYN_IMO_OFFSET_24MHZ_COLD_IMO_OFFSET_8_Msk 0xFFUL
/* SFLASH.DYN_IMO_OFFSET_28MHZ_COLD */
#define SFLASH_DYN_IMO_OFFSET_28MHZ_COLD_IMO_OFFSET_9_Pos 0UL
#define SFLASH_DYN_IMO_OFFSET_28MHZ_COLD_IMO_OFFSET_9_Msk 0xFFUL
/* SFLASH.DYN_IMO_OFFSET_32MHZ_COLD */
#define SFLASH_DYN_IMO_OFFSET_32MHZ_COLD_IMO_OFFSET_10_Pos 0UL
#define SFLASH_DYN_IMO_OFFSET_32MHZ_COLD_IMO_OFFSET_10_Msk 0xFFUL
/* SFLASH.DYN_IMO_OFFSET_36MHZ_COLD */
#define SFLASH_DYN_IMO_OFFSET_36MHZ_COLD_IMO_OFFSET_11_Pos 0UL
#define SFLASH_DYN_IMO_OFFSET_36MHZ_COLD_IMO_OFFSET_11_Msk 0xFFUL
/* SFLASH.DYN_IMO_OFFSET_40MHZ_COLD */
#define SFLASH_DYN_IMO_OFFSET_40MHZ_COLD_IMO_OFFSET_12_Pos 0UL
#define SFLASH_DYN_IMO_OFFSET_40MHZ_COLD_IMO_OFFSET_12_Msk 0xFFUL
/* SFLASH.DYN_IMO_OFFSET_44MHZ_COLD */
#define SFLASH_DYN_IMO_OFFSET_44MHZ_COLD_IMO_OFFSET_13_Pos 0UL
#define SFLASH_DYN_IMO_OFFSET_44MHZ_COLD_IMO_OFFSET_13_Msk 0xFFUL
/* SFLASH.DYN_IMO_OFFSET_48MHZ_COLD */
#define SFLASH_DYN_IMO_OFFSET_48MHZ_COLD_IMO_OFFSET_14_Pos 0UL
#define SFLASH_DYN_IMO_OFFSET_48MHZ_COLD_IMO_OFFSET_14_Msk 0xFFUL


#endif /* _CYIP_SFLASH_256_2_H_ */


/* [] END OF FILE */
