################################################################################
# \file bsp.mk
#
# \brief
# Define the KIT-PSC3M6-EVAL target.
#
################################################################################
# \copyright
# (c) 2022-2026, Infineon Technologies AG, or an affiliate of Infineon
# Technologies AG.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Any additional components to apply when using this board.
BSP_COMPONENTS:=

# Any additional defines to apply when using this board.
BSP_DEFINES:=
DEFINES+=CY_SYSTEM_CPU_M33

# Application type: ram or flash
APPTYPE?=flash

# SECURE or NON_SECURE. Default to SECURE if not defined
VCORE_ATTRS?=SECURE
# DEVICE_MODE is deprecated. This is for legacy support
ifneq ($(DEVICE_MODE),)
ifeq ($(filter $(DEVICE_MODE),$(VCORE_ATTRS)),)
VCORE_ATTRS+=$(DEVICE_MODE)
endif
endif

ifeq ($(filter SECURE,$(VCORE_ATTRS)),SECURE)
MTB_BSP__LINKER_SCRIPT=$(MTB_TOOLS__TARGET_DIR)/TOOLCHAIN_$(TOOLCHAIN)/linker_s_$(APPTYPE).$(MTB_RECIPE__SUFFIX_LS)
COMPONENTS+=SECURE_DEVICE
else ifeq ($(filter NON_SECURE,$(VCORE_ATTRS)),NON_SECURE)
MTB_BSP__LINKER_SCRIPT=$(MTB_TOOLS__TARGET_DIR)/TOOLCHAIN_$(TOOLCHAIN)/linker_ns_$(APPTYPE).$(MTB_RECIPE__SUFFIX_LS)
COMPONENTS+=NON_SECURE_DEVICE
endif

# Include memory boundaries definitions for the selected core
-include $(MTB_TOOLS__TARGET_DIR)/config/GeneratedSource/cymem_memory_locations.mk

# MCUBoot header size. Default is 0 (no MCUBoot header).
# Set to required size (e.g., 0x400) when using MCUBoot.
MCUBOOT_HEADER_SIZE?=0x0
DEFINES+=MCUBOOT_HEADER_SIZE=$(MCUBOOT_HEADER_SIZE)

# Ideally should come from recipe. Needed for finding the linker scripts generated through the memory configurator
ifneq (,$(filter $(TOOLCHAIN),GCC_ARM LLVM_ARM))
LDFLAGS+=-Wl,--defsym=MCUBOOT_HEADER_SIZE=$(MCUBOOT_HEADER_SIZE)
# To pick up generated .ld files
LDFLAGS += -L $(MTB_TOOLS__TARGET_DIR)/COMPONENT_CM33/TOOLCHAIN_$(TOOLCHAIN)
LDFLAGS += -L $(MTB_TOOLS__TARGET_DIR)/config/GeneratedSource
endif

ifeq ($(TOOLCHAIN),IAR)
LDFLAGS+=--config_def=MCUBOOT_HEADER_SIZE=$(MCUBOOT_HEADER_SIZE)
endif

ifeq ($(TOOLCHAIN),ARM)
LDFLAGS+=--predefine "-DMCUBOOT_HEADER_SIZE=$(MCUBOOT_HEADER_SIZE)"
LDFLAGS += --undefined=__scatterload_copy
endif
# Generate binary image
ifneq (,$(MTB_IDE__TARG_FILE))
_MTB_BSP__TARG_FILE:=$(call mtb__path_normalize,$(MTB_IDE__TARG_FILE))
else
_MTB_BSP__TARG_FILE=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/$(APPNAME).$(MTB_RECIPE__SUFFIX_TARGET)
endif

ifeq ($(TOOLCHAIN),ARM)
CY_BSP_POSTBUILD+=$(MTB_TOOLCHAIN_ARM__BASE_DIR)/bin/fromelf --output=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/$(APPNAME).bin --bincombined $(_MTB_BSP__TARG_FILE);
else
CY_BSP_POSTBUILD+=$(MTB_TOOLCHAIN_GCC_ARM__BASE_DIR)/bin/arm-none-eabi-objcopy -O binary $(_MTB_BSP__TARG_FILE) $(MTB_TOOLS__OUTPUT_CONFIG_DIR)/$(APPNAME).bin;
endif

# Enable JLink debugger
BSP_PROGRAM_INTERFACE?=JLink

# Linker warning suppressed for GCC 14.
# GCC 14 may produce "warning: <application>.elf has a LOAD segment with RWX permissions"
# which can be safely ignored there is no functional impact.
# See KBA: https://community.infineon.com/t5/Knowledge-Base-Articles/GCC-14-warnings-when-using-ModusToolbox/ta-p/1044532
ifeq ($(TOOLCHAIN),GCC_ARM)
	GCC_ARM_MAJOR := $(shell $(CY_TOOL_gcc_BASE_ABS)/bin/arm-none-eabi-gcc -dumpversion | cut -d. -f1)
	ifeq ($(GCC_ARM_MAJOR),14)
		LDFLAGS+=-Wl,--no-warn-rwx-segments
	endif
endif

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=
